const mapState={articles:[],view:'matrix',filters:{domain:'',document_class:'',route:''}};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const fmt=value=>new Intl.NumberFormat('pt-BR').format(Number(value||0));

const DOMAIN_ORDER=['nutrition_assessment','dietary_counseling','nutrition_prescription','monitoring_follow_up','food_skills_competencies','food_literacy','social_context','food_based_guidance','nutrition_care_process','lifestyle_medicine','implementation_practice'];
const DOMAIN_LABELS={nutrition_assessment:'Avaliação nutricional',dietary_counseling:'Aconselhamento alimentar',nutrition_prescription:'Prescrição nutricional',monitoring_follow_up:'Monitoramento / seguimento',food_skills_competencies:'Competências alimentares',food_literacy:'Food / nutrition literacy',social_context:'Contexto social da alimentação',food_based_guidance:'Orientação baseada em alimentos',nutrition_care_process:'Nutrition Care Process',lifestyle_medicine:'Medicina do Estilo de Vida',implementation_practice:'Implementação na prática'};
const CLASS_ORDER=['food_based_dietary_guideline','clinical_practice_guideline','consensus_statement','position_statement','framework_model','competency_curriculum','evidence_synthesis','implementation_evaluation','primary_observational','primary_randomized','primary_qualitative','unclassified'];
const CLASS_LABELS={food_based_dietary_guideline:'FBDG',clinical_practice_guideline:'Diretriz clínica',consensus_statement:'Consenso',position_statement:'Position statement',framework_model:'Framework/modelo',competency_curriculum:'Competências/currículo',evidence_synthesis:'Síntese de evidência',implementation_evaluation:'Implementação',primary_observational:'Observacional',primary_randomized:'Randomizado',primary_qualitative:'Qualitativo',unclassified:'Não classificado',review:'Revisão',guidance:'Guidance'};

function documentClass(row){return row.review_profile?.primary_document_class||row.document_class||'unclassified'}
function domains(row){return row.review_profile?.operational_domains||[]}
function routes(row){return row.routes||[]}
function isRouteMatch(row,route){if(!route)return true;const values=routes(row);if(route==='OVERLAP')return values.includes('B-NORM')&&values.includes('C-STRUCT');if(route==='UNROUTED')return values.length===0;return values.includes(route)}
function unique(values){return [...new Set(values.filter(Boolean))]}

function hydrateFromUrl(){const params=new URLSearchParams(location.search);const requestedView=params.get('view');if(['matrix','route','timeline'].includes(requestedView))mapState.view=requestedView;mapState.filters.domain=params.get('domain')||'';mapState.filters.document_class=params.get('document_class')||'';mapState.filters.route=params.get('route')||''}
function syncUrl(){const params=new URLSearchParams();if(mapState.view!=='matrix')params.set('view',mapState.view);for(const [key,value] of Object.entries(mapState.filters))if(value)params.set(key,value);history.replaceState(null,'',`${location.pathname}${params.toString()?`?${params}`:''}`)}

function filteredRows({ignoreDomain=false,ignoreClass=false}={}){const f=mapState.filters;return mapState.articles.filter(row=>{if(!ignoreDomain&&f.domain&&!domains(row).includes(f.domain))return false;if(!ignoreClass&&f.document_class&&documentClass(row)!==f.document_class)return false;if(!isRouteMatch(row,f.route))return false;return true})}

function populateControls(){const availableDomains=unique(mapState.articles.flatMap(domains));const availableClasses=unique(mapState.articles.map(documentClass));$('#mapDomainFilter').insertAdjacentHTML('beforeend',DOMAIN_ORDER.filter(value=>availableDomains.includes(value)).map(value=>`<option value="${esc(value)}">${esc(DOMAIN_LABELS[value]||value)}</option>`).join(''));const classes=[...CLASS_ORDER.filter(value=>availableClasses.includes(value)),...availableClasses.filter(value=>!CLASS_ORDER.includes(value))];$('#mapClassFilter').insertAdjacentHTML('beforeend',classes.map(value=>`<option value="${esc(value)}">${esc(CLASS_LABELS[value]||value)}</option>`).join(''));$('#mapDomainFilter').value=mapState.filters.domain;$('#mapClassFilter').value=mapState.filters.document_class;$('#mapRouteFilter').value=mapState.filters.route}

function updateSummary(){const rows=filteredRows();const parts=[];if(mapState.filters.domain)parts.push(DOMAIN_LABELS[mapState.filters.domain]||mapState.filters.domain);if(mapState.filters.document_class)parts.push(CLASS_LABELS[mapState.filters.document_class]||mapState.filters.document_class);if(mapState.filters.route)parts.push(mapState.filters.route);$('#mapFilterSummary').innerHTML=`<strong>${fmt(rows.length)}</strong><span> de ${fmt(mapState.articles.length)} documentos Tier A no recorte atual${parts.length?` · ${esc(parts.join(' · '))}`:''}</span>`}

function matrixCellRows(domain,docClass){return filteredRows({ignoreDomain:true,ignoreClass:true}).filter(row=>domains(row).includes(domain)&&documentClass(row)===docClass)}
function renderMatrix(){const base=filteredRows({ignoreDomain:true,ignoreClass:true});const availableClasses=unique(base.map(documentClass));const columns=[...CLASS_ORDER.filter(value=>availableClasses.includes(value)),...availableClasses.filter(value=>!CLASS_ORDER.includes(value))];const rows=DOMAIN_ORDER.filter(domain=>base.some(row=>domains(row).includes(domain)));let max=1;const counts={};for(const domain of rows){counts[domain]={};for(const docClass of columns){const value=matrixCellRows(domain,docClass).length;counts[domain][docClass]=value;max=Math.max(max,value)}}const head=`<thead><tr><th scope="col" class="matrix-corner">Operational domain</th>${columns.map(value=>`<th scope="col" title="${esc(CLASS_LABELS[value]||value)}">${esc(CLASS_LABELS[value]||value)}</th>`).join('')}</tr></thead>`;const body=`<tbody>${rows.map(domain=>`<tr><th scope="row">${esc(DOMAIN_LABELS[domain]||domain)}</th>${columns.map(docClass=>{const count=counts[domain][docClass];const heat=count?Math.max(.12,count/max):0;const selected=mapState.filters.domain===domain&&mapState.filters.document_class===docClass;return `<td><button type="button" class="matrix-cell${selected?' selected':''}${count?' has-docs':' empty'}" data-domain="${esc(domain)}" data-document-class="${esc(docClass)}" style="--heat:${heat}" title="${esc(DOMAIN_LABELS[domain]||domain)} × ${esc(CLASS_LABELS[docClass]||docClass)}: ${fmt(count)} documentos. Contagem não representa força da evidência."><strong>${fmt(count)}</strong><span>${count?'documentos':'no documents mapped'}</span></button></td>`}).join('')}</tr>`).join('')}</tbody>`;$('#evidenceMatrix').innerHTML=head+body}

function renderRouteMatrix(){const base=filteredRows({ignoreDomain:true});const rows=DOMAIN_ORDER.filter(domain=>base.some(row=>domains(row).includes(domain)));const routeCount=(domain,route)=>base.filter(row=>domains(row).includes(domain)&&isRouteMatch(row,route)).length;$('#routeMatrix').innerHTML=rows.length?`<div class="route-map-head"><span>Domínio</span><span>B-NORM</span><span>C-STRUCT</span><span>Overlap</span><span>Unrouted</span></div>${rows.map(domain=>`<div class="route-map-row"><strong>${esc(DOMAIN_LABELS[domain]||domain)}</strong>${['B-NORM','C-STRUCT','OVERLAP','UNROUTED'].map(route=>`<button type="button" data-route-cell="${route}" data-domain="${esc(domain)}"><b>${fmt(routeCount(domain,route))}</b><span>${route==='UNROUTED'?'not routed':route}</span></button>`).join('')}</div>`).join('')}`:'<div class="small-state">Nenhum documento neste recorte.</div>'}

function renderTimeline(){const rows=filteredRows();const counts={};for(const row of rows){const year=Number(row.year);if(year>=1900&&year<=2100)counts[year]=(counts[year]||0)+1}const entries=Object.entries(counts).map(([year,value])=>[Number(year),value]).sort((a,b)=>a[0]-b[0]);if(!entries.length){$('#mapTimeline').innerHTML='<div class="small-state">Ano de publicação não disponível neste recorte.</div>';$('#mapTimelineAxis').innerHTML='';return}const max=Math.max(...entries.map(([,value])=>value));$('#mapTimeline').innerHTML=entries.map(([year,value])=>`<div class="map-timeline-bar" style="height:${Math.max(3,100*value/max)}%" title="${year}: ${fmt(value)} documentos"><span class="sr-only">${year}: ${fmt(value)} documentos</span></div>`).join('');$('#mapTimelineAxis').innerHTML=`<span>${entries[0][0]}</span><span>${entries[Math.floor(entries.length/2)][0]}</span><span>${entries.at(-1)[0]}</span>`}

function explorerHref(){const params=new URLSearchParams();if(mapState.filters.domain)params.set('domain',mapState.filters.domain);if(mapState.filters.document_class)params.set('document_class',mapState.filters.document_class);if(mapState.filters.route&&['B-NORM','C-STRUCT'].includes(mapState.filters.route))params.set('route',mapState.filters.route);if(mapState.filters.domain)return `/evidence.html?${params}`;if(mapState.filters.document_class)return `/articles.html?document_class=${encodeURIComponent(mapState.filters.document_class)}`;return '/evidence.html'}
function renderSelectedDocuments(){const rows=filteredRows();$('#selectedDocumentsMeta').textContent=`${fmt(rows.length)} documentos no recorte atual · lista limitada aos 40 primeiros para navegação visual.`;$('#selectedDocumentsOpen').href=explorerHref();$('#selectedDocuments').innerHTML=rows.slice(0,40).map(row=>`<article class="map-document"><div><strong>${esc(row.title||'Sem título')}</strong><small>${esc([row.year,row.source_provider,CLASS_LABELS[documentClass(row)]||documentClass(row)].filter(Boolean).join(' · '))}</small></div><div class="detail-chips">${routes(row).map(value=>`<span class="mini-pill">${esc(value)}</span>`).join('')}</div></article>`).join('')||'<div class="small-state">Nenhum documento mapeado neste recorte.</div>'}

function renderView(){document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===mapState.view));$('#matrixView').classList.toggle('hidden',mapState.view!=='matrix');$('#routeView').classList.toggle('hidden',mapState.view!=='route');$('#timelineView').classList.toggle('hidden',mapState.view!=='timeline');updateSummary();renderMatrix();renderRouteMatrix();renderTimeline();renderSelectedDocuments();syncUrl()}
function setFilters(patch){Object.assign(mapState.filters,patch);$('#mapDomainFilter').value=mapState.filters.domain;$('#mapClassFilter').value=mapState.filters.document_class;$('#mapRouteFilter').value=mapState.filters.route;renderView()}

function bindEvents(){$('#mapViewTabs').addEventListener('click',event=>{const button=event.target.closest('[data-view]');if(!button)return;mapState.view=button.dataset.view;renderView()});$('#mapDomainFilter').addEventListener('change',event=>setFilters({domain:event.target.value}));$('#mapClassFilter').addEventListener('change',event=>setFilters({document_class:event.target.value}));$('#mapRouteFilter').addEventListener('change',event=>setFilters({route:event.target.value}));$('#clearMapFilters').addEventListener('click',()=>setFilters({domain:'',document_class:'',route:''}));$('#evidenceMatrix').addEventListener('click',event=>{const button=event.target.closest('[data-domain][data-document-class]');if(!button)return;setFilters({domain:button.dataset.domain,document_class:button.dataset.documentClass})});$('#routeMatrix').addEventListener('click',event=>{const button=event.target.closest('[data-route-cell][data-domain]');if(!button)return;setFilters({domain:button.dataset.domain,route:button.dataset.routeCell})})}

async function loadArticle1Summaries(){const statusResponse=await fetch('/api/agent-context/article1/status',{cache:'no-store'});if(!statusResponse.ok)throw new Error(`status HTTP ${statusResponse.status}`);const status=await statusResponse.json();if(!status.available){const missing=Array.isArray(status.missing_files)?status.missing_files.join(', '):'bundle incompleto';throw new Error(`contexto científico não materializado: ${missing}`)}const baseUrl=String(status.base_url||'/agent-context/article1/');const response=await fetch(`${baseUrl}ARTICLE_SUMMARIES.jsonl`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);return (await response.text()).split(/\r?\n/).filter(Boolean).map(JSON.parse)}

async function init(){hydrateFromUrl();try{mapState.articles=await loadArticle1Summaries();const availableDomains=new Set(mapState.articles.flatMap(domains));const availableClasses=new Set(mapState.articles.map(documentClass));if(mapState.filters.domain&&!availableDomains.has(mapState.filters.domain))mapState.filters.domain='';if(mapState.filters.document_class&&!availableClasses.has(mapState.filters.document_class))mapState.filters.document_class='';populateControls();bindEvents();renderView();$('#mapState').className='hidden';$('#mapContent').classList.remove('hidden');$('#mapHealth').textContent=`${fmt(mapState.articles.length)} resumos verificados`;$('#mapHealth').className='status-pill ok'}catch(error){$('#mapState').className='warning';$('#mapState').innerHTML=`<strong>Evidence Map ainda sem contexto materializado.</strong><div>${esc(error.message)}</div>`;$('#mapHealth').textContent='contexto não materializado';$('#mapHealth').className='status-pill'}}

init();
