import './i18n.js'

const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const fmt=value=>new Intl.NumberFormat('pt-BR').format(Number(value||0));
const classLabels={food_based_dietary_guideline:'FBDG',clinical_practice_guideline:'Diretriz clínica',consensus_statement:'Consenso',position_statement:'Position statement',framework_model:'Framework/modelo',competency_curriculum:'Competências/currículo',implementation_evaluation:'Implementação',primary_randomized:'Randomizado',primary_observational:'Observacional',primary_qualitative:'Qualitativo',evidence_synthesis:'Síntese de evidência',review:'Revisão',guidance:'Guidance',unclassified:'Não classificado'};
const domainLabels={nutrition_assessment:'Avaliação nutricional',dietary_counseling:'Aconselhamento alimentar',nutrition_prescription:'Prescrição nutricional',monitoring_follow_up:'Monitoramento / seguimento',food_skills_competencies:'Competências alimentares',food_literacy:'Food / nutrition literacy',social_context:'Contexto social',food_based_guidance:'Orientação baseada em alimentos',nutrition_care_process:'Nutrition Care Process',lifestyle_medicine:'Lifestyle Medicine',implementation_practice:'Implementação'};
const params=new URLSearchParams(location.search);
let articles=[];
const requestedRoute=params.get('route');
let route=['B-NORM','C-STRUCT'].includes(requestedRoute)?requestedRoute:'B-NORM';
let view=params.get('view')==='compare'?'compare':'route';

function cls(row){return row.review_profile?.primary_document_class||row.document_class||'unclassified'}
function domains(row){return row.review_profile?.operational_domains||[]}
function routes(row){return row.routes||[]}
function routeRows(name){return articles.filter(row=>routes(row).includes(name))}
function overlapRows(){return articles.filter(row=>routes(row).includes('B-NORM')&&routes(row).includes('C-STRUCT'))}
function exclusiveRows(name){const other=name==='B-NORM'?'C-STRUCT':'B-NORM';return articles.filter(row=>routes(row).includes(name)&&!routes(row).includes(other))}
function countBy(rows,getter){const out={};for(const row of rows){const key=getter(row);if(!key)continue;out[key]=(out[key]||0)+1}return out}
function syncRouteUrl(){for(const key of [...params.keys()])params.delete(key);if(view==='compare')params.set('view','compare');else params.set('route',route);history.replaceState(null,'',`${location.pathname}${params.toString()?`?${params}`:''}`)}
function barRows(left,right,labels,limit=8){const keys=[...new Set([...Object.keys(left),...Object.keys(right)])].sort((a,b)=>(right[b]||0)+(left[b]||0)-(right[a]||0)-(left[a]||0)).slice(0,limit);const max=Math.max(1,...keys.flatMap(key=>[left[key]||0,right[key]||0]));return `<div class="compare-bars">${keys.map(key=>`<div class="compare-bar-row"><span>${esc(labels[key]||key)}</span><div class="compare-pair"><i class="b" style="width:${100*(left[key]||0)/max}%"></i><i class="c" style="width:${100*(right[key]||0)/max}%"></i></div><small><b>${fmt(left[key]||0)}</b> / <b>${fmt(right[key]||0)}</b></small></div>`).join('')}</div>`}

async function init(){try{const response=await fetch('/agent-context/article1/ARTICLE_SUMMARIES.jsonl',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);articles=(await response.text()).split(/\r?\n/).filter(Boolean).map(JSON.parse);$('#routeState').className='hidden';$('#routeContent').classList.remove('hidden');$('#routeHealth').textContent=`${fmt(articles.length)} resumos verificados`;$('#routeHealth').className='status-pill ok';render()}catch(error){$('#routeState').className='error';$('#routeState').innerHTML=`<strong>Review Routes indisponível.</strong><div>${esc(error.message)}</div>`;$('#routeHealth').textContent='contexto indisponível';$('#routeHealth').className='status-pill bad'}}

function renderKpis(){const b=routeRows('B-NORM'),c=routeRows('C-STRUCT'),overlap=overlapRows(),union=articles.filter(row=>routes(row).length),exclusiveB=exclusiveRows('B-NORM'),exclusiveC=exclusiveRows('C-STRUCT'),unrouted=articles.filter(row=>routes(row).length===0);const items=[['B-NORM',b.length],['C-STRUCT',c.length],['Overlap',overlap.length],['Exclusive B',exclusiveB.length],['Exclusive C',exclusiveC.length],['Unrouted',unrouted.length]];$('#routeKpis').innerHTML=items.map(([label,value])=>`<article class="card metric-card"><span class="metric-label">${esc(label)}</span><strong class="metric-value">${fmt(value)}</strong></article>`).join('')}
function renderRoute(){const rows=routeRows(route);const classes=countBy(rows,cls);const mix=Object.entries(classes).sort((a,b)=>b[1]-a[1]).slice(0,8);$('#activeRouteTitle').textContent=route;$('#activeRouteMeta').textContent=`${fmt(rows.length)} documentos roteados · ordem desta tela não é Bank rank`;$('#routeEvidenceLink').href=`/evidence.html?route=${encodeURIComponent(route)}`;$('#routeClassMix').innerHTML=mix.map(([key,value])=>`<span class="mini-pill">${esc(classLabels[key]||key)} · ${fmt(value)}</span>`).join('');$('#routeList').innerHTML=rows.map((row,index)=>`<article class="review-route-row"><div class="route-seq">${fmt(index+1)}</div><div><strong data-article-title>${esc(row.title||'Sem título')}</strong><small>${esc([row.year,row.source_provider,classLabels[cls(row)]].filter(Boolean).join(' · '))}</small><div class="detail-chips">${domains(row).slice(0,4).map(value=>`<a class="mini-pill" href="/evidence.html?domain=${encodeURIComponent(value)}&route=${encodeURIComponent(route)}">${esc(domainLabels[value]||value)}</a>`).join('')}</div></div></article>`).join('')||'<p class="small-state">Nenhum documento nesta rota.</p>';$('#routeGuardrail').textContent=`${route} é uma fila de leitura/navegação. Permanecer nesta rota não significa inclusão; ficar fora dela não significa exclusão.`}
function renderComparison(){const b=routeRows('B-NORM'),c=routeRows('C-STRUCT'),overlap=overlapRows();$('#compareClasses').innerHTML=barRows(countBy(b,cls),countBy(c,cls),classLabels,10);$('#compareFulltext').innerHTML=barRows(countBy(b,row=>row.full_text_status||'unknown'),countBy(c,row=>row.full_text_status||'unknown'),{retrieved:'Retrieved',partial:'Partial',not_retrieved:'Not retrieved',unavailable:'Unavailable',unknown:'Unknown'},8);$('#compareProviders').innerHTML=barRows(countBy(b,row=>row.source_provider||'unknown'),countBy(c,row=>row.source_provider||'unknown'),{},8);const domainKeys=[...new Set([...b.flatMap(domains),...c.flatMap(domains)])].sort((a,z)=>(domainLabels[a]||a).localeCompare(domainLabels[z]||z));$('#compareDomains').innerHTML=domainKeys.map(domain=>{const bv=b.filter(row=>domains(row).includes(domain)).length,cv=c.filter(row=>domains(row).includes(domain)).length,ov=overlap.filter(row=>domains(row).includes(domain)).length;return `<tr><th>${esc(domainLabels[domain]||domain)}</th><td>${fmt(bv)}</td><td>${fmt(cv)}</td><td>${fmt(ov)}</td><td>${cv-bv>=0?'+':''}${fmt(cv-bv)}</td><td><a href="/evidence.html?domain=${encodeURIComponent(domain)}">Open ↗</a></td></tr>`}).join('');renderTimeline(b,c);renderSets()}
function renderTimeline(b,c){const years=[...new Set([...b,...c].map(row=>Number(row.year)).filter(year=>year>=1900&&year<=2100))].sort((a,z)=>a-z);if(!years.length){$('#compareTimeline').innerHTML='<div class="small-state">Ano indisponível.</div>';return}const bCounts=countBy(b,row=>String(row.year||'')),cCounts=countBy(c,row=>String(row.year||'')),max=Math.max(1,...years.flatMap(year=>[bCounts[year]||0,cCounts[year]||0]));$('#compareTimeline').innerHTML=years.map(year=>`<div class="route-year" title="${year} · B ${bCounts[year]||0} · C ${cCounts[year]||0}"><i class="b" style="height:${100*(bCounts[year]||0)/max}%"></i><i class="c" style="height:${100*(cCounts[year]||0)/max}%"></i></div>`).join('');$('#compareTimelineAxis').innerHTML=`<span>${years[0]}</span><span>${years[Math.floor(years.length/2)]}</span><span>${years.at(-1)}</span>`}
function renderSets(){const groups=[['Exclusive B-NORM',exclusiveRows('B-NORM')],['Overlap',overlapRows()],['Exclusive C-STRUCT',exclusiveRows('C-STRUCT')]];$('#compareSets').innerHTML=groups.map(([label,rows])=>`<article class="set-card"><span>${esc(label)}</span><strong>${fmt(rows.length)}</strong><small data-nutev-no-translate>${esc(rows.slice(0,3).map(row=>row.title||'Sem título').join(' · '))}${rows.length>3?' …':''}</small></article>`).join('')}
function render(){renderKpis();document.querySelectorAll('[data-route]').forEach(button=>button.classList.toggle('active',view==='route'&&button.dataset.route===route));const compareButton=document.querySelector('[data-view="compare"]');if(compareButton)compareButton.classList.toggle('active',view==='compare');$('#routeListView').classList.toggle('hidden',view!=='route');$('#routeCompareView').classList.toggle('hidden',view!=='compare');if(view==='compare')renderComparison();else renderRoute();syncRouteUrl()}

$('#routeTabs').addEventListener('click',event=>{const routeButton=event.target.closest('[data-route]');if(routeButton){route=routeButton.dataset.route;view='route';render();return}const compare=event.target.closest('[data-view="compare"]');if(compare){view='compare';render()}});
init();