"""Identity, authentication, and authorization contracts for NutEV multi-tenant boundaries."""

from .auth import (
    AUTH_SCHEMA_VERSION,
    DEFAULT_SESSION_TTL_SECONDS,
    AuthDataError,
    AuthProvider,
    AuthenticatedSubject,
    IssuedSession,
    LoginResult,
    SessionPrincipal,
    SessionPrincipalService,
    SessionRecord,
    SQLiteAuthProvider,
    SQLiteSessionStore,
)
from .models import (
    GlobalRole,
    Membership,
    MembershipStatus,
    Principal,
    Project,
    ResearchApplication,
    User,
    Workspace,
    WorkspaceMembership,
    WorkspaceRole,
    new_opaque_id,
    require_opaque_id,
)
from .permissions import (
    AuthorizationContext,
    Permission,
    PermissionDecision,
    PermissionDenied,
    PermissionRule,
    PermissionScope,
    PermissionService,
    ROLE_PERMISSIONS,
)

__all__ = [
    "AUTH_SCHEMA_VERSION",
    "AuthorizationContext",
    "AuthDataError",
    "AuthProvider",
    "AuthenticatedSubject",
    "DEFAULT_SESSION_TTL_SECONDS",
    "GlobalRole",
    "IssuedSession",
    "LoginResult",
    "Membership",
    "MembershipStatus",
    "Permission",
    "PermissionDecision",
    "PermissionDenied",
    "PermissionRule",
    "PermissionScope",
    "PermissionService",
    "Principal",
    "Project",
    "ROLE_PERMISSIONS",
    "ResearchApplication",
    "SQLiteAuthProvider",
    "SQLiteSessionStore",
    "SessionPrincipal",
    "SessionPrincipalService",
    "SessionRecord",
    "User",
    "Workspace",
    "WorkspaceMembership",
    "WorkspaceRole",
    "new_opaque_id",
    "require_opaque_id",
]
