from __future__ import annotations

from collections.abc import Iterable


SCORING_FIELDS = (
    "title",
    "abstract",
    "snippet",
    "evidence_type",
    "category",
)

BONUS_TERMS: tuple[tuple[str, float], ...] = (
    ("standards of medical care in diabetes", 60),
    ("clinical practice guideline", 60),
    ("practice guideline", 55),
    ("practical guideline", 50),
    ("guideline update", 60),
    ("living guideline", 55),
    ("guideline", 50),
    ("food-based dietary guideline", 45),
    ("food based dietary guideline", 45),
    ("food guide", 40),
    ("nutrition guideline", 40),
    ("scientific statement", 45),
    ("scientific advisory", 45),
    ("consensus", 45),
    ("consensus report", 45),
    ("consensus guidance", 45),
    ("expert consensus", 45),
    ("practice advisory", 45),
    ("practice guidance", 42),
    ("guidance statement", 42),
    ("joint statement", 40),
    ("joint guideline", 42),
    ("position statement", 40),
    ("position paper", 40),
    ("clinical guidance", 40),
    ("practice recommendation", 40),
    ("evidence-based recommendation", 40),
    ("evidence based recommendation", 40),
    ("best practice advice", 40),
    ("standards of care", 45),
    ("clinical pathway", 40),
    ("care pathway", 35),
    ("clinical decision pathway", 40),
    ("decision pathway", 35),
    ("systematic review", 35),
    ("living systematic review", 35),
    ("meta-analysis", 35),
    ("meta analysis", 35),
    ("network meta-analysis", 35),
    ("network meta analysis", 35),
    ("umbrella review", 35),
    ("overview of reviews", 35),
    ("review of reviews", 35),
    ("rapid review", 30),
    ("scoping review", 30),
    ("randomized trial", 30),
    ("randomised trial", 30),
    ("pragmatic trial", 30),
    ("pragmatic clinical trial", 30),
    ("pragmatic randomized trial", 30),
    ("pragmatic randomised trial", 30),
    ("implementation trial", 24),
    ("effectiveness-implementation trial", 24),
    ("effectiveness implementation trial", 24),
    ("implementation-effectiveness trial", 24),
    ("implementation effectiveness trial", 24),
    ("hybrid effectiveness-implementation trial", 24),
    ("hybrid effectiveness implementation trial", 24),
    ("real-world effectiveness", 18),
    ("real world effectiveness", 18),
    ("trial", 18),
    ("official report", 25),
    ("questionnaire validation", 20),
    ("psychometric", 20),
    ("scale development", 18),
    ("survey instrument", 18),
    ("food literacy instrument", 18),
    ("nutrition literacy instrument", 18),
    ("culinary skills instrument", 18),
    ("food skills instrument", 18),
    ("food competence instrument", 18),
    ("cooking skills instrument", 18),
    ("cooking self-efficacy instrument", 18),
    ("cooking self efficacy instrument", 18),
    ("meal preparation instrument", 18),
    ("dietary adherence instrument", 18),
    ("dietary adherence questionnaire", 18),
    ("dietary adherence scale", 18),
    ("adherence questionnaire", 16),
    ("adherence scale", 16),
    ("eating behavior questionnaire", 16),
    ("eating behaviour questionnaire", 16),
    ("dietary behavior questionnaire", 16),
    ("dietary behaviour questionnaire", 16),
    ("nutrition behavior questionnaire", 16),
    ("nutrition behaviour questionnaire", 16),
    ("food choice questionnaire", 16),
    ("meal planning questionnaire", 14),
    ("meal preparation questionnaire", 14),
    ("food preparation questionnaire", 14),
    ("self-efficacy scale", 14),
    ("self efficacy scale", 14),
    ("cooking self-efficacy scale", 16),
    ("cooking self efficacy scale", 16),
    ("food literacy questionnaire", 16),
    ("nutrition literacy questionnaire", 16),
    ("culinary skills questionnaire", 16),
    ("food skills questionnaire", 16),
    ("food competence questionnaire", 16),
    ("cooking skills questionnaire", 16),
    ("cooking self-efficacy questionnaire", 16),
    ("cooking self efficacy questionnaire", 16),
    ("food literacy scale", 16),
    ("nutrition literacy scale", 16),
    ("culinary skills scale", 16),
    ("food skills scale", 16),
    ("food competence scale", 16),
    ("eating competence scale", 16),
    ("cooking confidence scale", 16),
    ("commensality scale", 14),
    ("shared meals scale", 12),
    ("family meals scale", 12),
    ("family mealtime scale", 12),
    ("eating competence", 14),
    ("food competence", 14),
    ("food and nutrition literacy", 15),
    ("food literacy", 15),
    ("nutrition literacy", 15),
    ("culinary medicine", 15),
    ("culinary medicine curriculum", 18),
    ("culinary medicine program", 18),
    ("culinary medicine programme", 18),
    ("culinary medicine evaluation", 18),
    ("culinary nutrition", 15),
    ("culinary nutrition intervention", 16),
    ("teaching kitchens", 15),
    ("teaching kitchen", 15),
    ("teaching kitchen program", 18),
    ("teaching kitchen programme", 18),
    ("food agency", 15),
    ("food budgeting", 12),
    ("food resource management", 12),
    ("food resource management questionnaire", 16),
    ("shopping skills", 10),
    ("grocery shopping skills", 12),
    ("healthy grocery shopping", 10),
    ("meal kit", 8),
    ("food label literacy", 12),
    ("retail food environment", 14),
    ("healthy food access", 12),
    ("healthy food procurement", 14),
    ("menu labeling", 12),
    ("menu labelling", 12),
    ("meal context", 10),
    ("meal routine", 10),
    ("meal routines", 10),
    ("meal sharing", 12),
    ("shared meal", 10),
    ("shared meals", 10),
    ("family meal", 10),
    ("family meals", 10),
    ("family mealtime", 10),
    ("family mealtimes", 10),
    ("eating together", 10),
    ("social eating", 10),
    ("commensality", 12),
    ("food is medicine", 18),
    ("food as medicine", 18),
    ("food as medicine intervention", 18),
    ("produce prescription program", 18),
    ("produce prescriptions", 18),
    ("produce prescription", 18),
    ("produce rx", 18),
    ("fruit and vegetable prescription", 18),
    ("healthy food prescription", 18),
    ("food prescription program", 18),
    ("healthy food incentives", 18),
    ("healthy food incentive", 18),
    ("nutrition incentives", 18),
    ("nutrition incentive", 18),
    ("produce vouchers", 18),
    ("produce voucher", 18),
    ("fruit and vegetable vouchers", 18),
    ("fruit and vegetable voucher", 18),
    ("grocery prescription", 18),
    ("grocery prescriptions", 18),
    ("food pharmacy", 18),
    ("food pharmacies", 18),
    ("food pharmacy program", 20),
    ("food farmacy", 18),
    ("food farmacies", 18),
    ("food farmacy program", 20),
    ("nutrition assistance program", 16),
    ("nutrition assistance programs", 16),
    ("nutrition security", 18),
    ("food and nutrition security", 18),
    ("nutrition security intervention", 20),
    ("nutrition security screening", 20),
    ("nutrition insecurity", 18),
    ("nutrition insecurity screening", 20),
    ("nutrition insecurity intervention", 20),
    ("food insecurity", 16),
    ("food insecurity screening", 20),
    ("screening for food insecurity", 20),
    ("screening and referral", 16),
    ("closed-loop referral", 16),
    ("closed loop referral", 16),
    ("screen and intervene", 18),
    ("hunger vital sign", 18),
    ("social needs screening", 16),
    ("social needs referral", 16),
    ("social prescribing", 18),
    ("social prescribing program", 20),
    ("food pantry referral", 18),
    ("food pantry referral program", 20),
    ("food bank partnership", 16),
    ("community food program", 16),
    ("community food programme", 16),
    ("community-supported food program", 16),
    ("community supported food program", 16),
    ("food access intervention", 18),
    ("healthy food access intervention", 18),
    ("food insecurity intervention", 18),
    ("social needs intervention", 16),
    ("community health worker", 16),
    ("community health worker-led nutrition", 18),
    ("community health worker led nutrition", 18),
    ("patient navigation", 16),
    ("care navigation", 16),
    ("social determinants of health", 16),
    ("health equity", 16),
    ("equity-focused intervention", 18),
    ("community-based intervention", 16),
    ("community based intervention", 16),
    ("cultural adaptation", 14),
    ("culturally adapted", 14),
    ("underserved populations", 14),
    ("low-income", 12),
    ("low income", 12),
    ("rural health", 12),
    ("primary care", 10),
    ("food desert", 12),
    ("food swamp", 12),
    ("food affordability", 12),
    ("healthy food affordability", 14),
    ("medically tailored meals", 18),
    ("medically tailored meal", 18),
    ("medically tailored groceries", 18),
    ("medically tailored grocery", 18),
    ("medically tailored pantries", 18),
    ("medically tailored pantry", 18),
    ("medically tailored food packages", 18),
    ("medically tailored food package", 18),
    ("medically tailored food referral", 18),
    ("produce prescription referral", 18),
    ("cooking skills", 12),
    ("food skills", 12),
    ("home cooking", 12),
    ("meal preparation", 12),
    ("meal preparation skills", 14),
    ("food preparation skills", 14),
    ("food preparation confidence", 14),
    ("cooking confidence", 12),
    ("cooking self-efficacy", 14),
    ("cooking self efficacy", 14),
    ("nutrition education", 12),
    ("nutrition label", 10),
    ("food label", 10),
    ("label reading", 10),
    ("front-of-pack labeling", 12),
    ("front-of-pack labelling", 12),
    ("front-of-pack", 10),
    ("dietary adherence", 15),
    ("treatment adherence", 15),
    ("adherence", 15),
    ("implementation science", 15),
    ("implementation research", 15),
    ("implementation strategies", 15),
    ("implementation strategy", 15),
    ("implementation frameworks", 15),
    ("implementation framework", 15),
    ("implementation outcomes framework", 15),
    ("proctor implementation outcomes", 15),
    ("implementation outcomes", 15),
    ("implementation trial", 16),
    ("implementation evaluation", 14),
    ("implementation fidelity", 15),
    ("implementation facilitation", 15),
    ("implementation support", 12),
    ("implementation determinants", 12),
    ("implementation determinant", 12),
    ("implementation barriers", 12),
    ("implementation barrier", 12),
    ("implementation facilitators", 12),
    ("implementation facilitator", 12),
    ("implementation climate", 12),
    ("organizational readiness", 14),
    ("readiness for implementation", 14),
    ("implementation", 15),
    ("acceptability", 12),
    ("appropriateness", 12),
    ("penetration", 10),
    ("sustainment", 12),
    ("hybrid effectiveness-implementation", 18),
    ("hybrid effectiveness implementation", 18),
    ("hybrid type 1", 16),
    ("hybrid type 2", 16),
    ("hybrid type 3", 16),
    ("consolidated framework for implementation research", 16),
    ("cfir", 14),
    ("re-aim", 14),
    ("normalization process theory", 14),
    ("theoretical domains framework", 14),
    ("motivational interviewing", 12),
    ("behavior change wheel", 14),
    ("behaviour change wheel", 14),
    ("com-b", 14),
    ("capability opportunity motivation behavior", 14),
    ("capability opportunity motivation behaviour", 14),
    ("intervention mapping", 14),
    ("implementation mapping", 14),
    ("process evaluation", 15),
    ("quality improvement study", 12),
    ("quality improvement", 10),
    ("program implementation", 10),
    ("scale-up", 12),
    ("scale up", 12),
    ("scale-out", 10),
    ("scale out", 10),
    ("knowledge translation", 15),
    ("behavioral lifestyle intervention", 15),
    ("behavioral weight loss", 15),
    ("behavioral intervention", 14),
    ("behavior change technique", 12),
    ("behavior change", 12),
    ("dietary behaviour", 12),
    ("dietary behavior", 12),
    ("eating behaviour", 12),
    ("eating behavior", 12),
    ("eating habits", 10),
    ("food choices", 10),
    ("food choice", 10),
    ("meal patterns", 10),
    ("meal pattern", 10),
    ("therapeutic lifestyle changes", 15),
    ("intensive lifestyle intervention", 16),
    ("lifestyle programme", 12),
    ("lifestyle program", 12),
    ("time-restricted eating", 12),
    ("time restricted eating", 12),
    ("intermittent fasting", 12),
    ("diabetes prevention program", 14),
    ("type 2 diabetes remission", 20),
    ("remission of type 2 diabetes", 20),
    ("diabetes remission", 20),
    ("diabetes reversal", 18),
    ("glycemic remission", 18),
    ("glycaemic remission", 18),
    ("weight regain prevention", 16),
    ("weight regain management", 14),
    ("weight regain", 14),
    ("weight maintenance", 14),
    ("behavioral maintenance", 12),
    ("behavioral maintenance intervention", 14),
    ("dietary maintenance", 12),
    ("dietary maintenance intervention", 14),
    ("relapse prevention", 12),
    ("lapse management", 10),
    ("dietary self-monitoring", 12),
    ("dietary self-regulation", 12),
    ("long-term weight loss maintenance", 14),
    ("long term weight loss maintenance", 14),
    ("nutrition care for diabetes remission", 20),
    ("nutrition care for weight maintenance", 18),
    ("dietitian-led remission", 18),
    ("dietitian led remission", 18),
    ("medical nutrition therapy guideline", 24),
    ("medical nutrition therapy consensus", 22),
    ("nutrition care pathway guideline", 24),
    ("nutrition care protocol guideline", 24),
    ("nutrition care consensus", 22),
    ("nutrition prescription", 16),
    ("nutrition prescriptions", 16),
    ("diet prescription", 16),
    ("diet prescriptions", 16),
    ("dietary prescription", 16),
    ("dietary prescriptions", 16),
    ("personalized nutrition", 14),
    ("personalised nutrition", 14),
    ("precision nutrition", 14),
    ("tailored nutrition", 14),
    ("tailored dietary advice", 14),
    ("tailored dietary intervention", 14),
    ("personalized dietary advice", 14),
    ("personalised dietary advice", 14),
    ("personalized dietary intervention", 14),
    ("personalised dietary intervention", 14),
    ("personalized meal planning", 14),
    ("personalised meal planning", 14),
    ("individualized diet", 14),
    ("individualised diet", 14),
    ("individualized dietary intervention", 14),
    ("individualised dietary intervention", 14),
    ("individualized meal plan", 14),
    ("individualised meal plan", 14),
    ("diet personalization", 14),
    ("diet personalisation", 14),
    ("self-management support", 12),
    ("self-management", 12),
    ("self management", 12),
    ("shared decision making", 12),
    ("health coaching", 12),
    ("practice facilitation", 14),
    ("weight loss maintenance", 12),
    ("healthy eating pattern", 12),
    ("diet quality", 10),
    ("dietary pattern", 10),
    ("goal setting", 12),
    ("social support", 12),
    ("food access", 12),
    ("lifestyle counseling", 12),
    ("lifestyle counselling", 12),
    ("medical nutrition therapy", 15),
    ("nutrition counseling", 12),
    ("nutrition counselling", 12),
    ("dietary counseling", 12),
    ("dietary counselling", 12),
    ("nutrition care process model", 14),
    ("nutrition care process", 14),
    ("nutrition care pathways", 16),
    ("nutrition care pathway", 16),
    ("nutrition care protocols", 14),
    ("nutrition care protocol", 14),
    ("nutrition care", 10),
    ("registered dietitian nutritionist-led intervention", 18),
    ("registered dietitian nutritionist led intervention", 18),
    ("registered dietitian-led intervention", 18),
    ("registered dietitian led intervention", 18),
    ("dietitian-delivered intervention", 16),
    ("dietitian delivered intervention", 16),
    ("dietitian-managed intervention", 16),
    ("dietitian managed intervention", 16),
    ("registered dietitian nutritionist", 12),
    ("registered dietitian", 12),
    ("dietitian-led", 12),
    ("dietitian led", 12),
    ("digital therapeutics", 14),
    ("telemedicine", 14),
    ("telehealth", 14),
    ("digital health", 14),
    ("mobile health", 12),
    ("mhealth", 12),
    ("ehealth", 12),
    ("virtual care", 12),
    ("remote coaching", 12),
    ("remote monitoring", 12),
    ("feasibility", 15),
    ("sustainability", 12),
    ("dissemination", 12),
    ("adoption", 10),
    ("reach", 10),
    ("maintenance", 10),
    ("real-world implementation", 12),
    ("real world implementation", 12),
    ("real-world evidence", 12),
    ("real world evidence", 12),
    ("audit and feedback", 14),
    ("service delivery", 10),
    ("care delivery", 10),
    ("food environment", 15),
    ("barriers and facilitators", 12),
    ("dietary approaches to stop hypertension", 12),
    ("mediterranean dietary pattern", 12),
    ("mediterranean diet", 12),
    ("mind diet", 12),
    ("portfolio diet", 12),
    ("new nordic diet", 12),
    ("nordic diet", 12),
    ("plant-based", 12),
    ("plant based diet", 12),
    ("healthy plant-based diet", 12),
    ("healthy plant based diet", 12),
    ("whole-food plant-based", 12),
    ("whole food plant based", 12),
    ("vegetarian dietary pattern", 12),
    ("vegetarian diet", 12),
    ("vegan dietary pattern", 12),
    ("vegan diet", 12),
    ("provegetarian dietary pattern", 12),
    ("pro-vegetarian dietary pattern", 12),
    ("low-carbohydrate diet", 12),
    ("low carbohydrate diet", 12),
    ("low-carb diet", 12),
    ("very-low-carbohydrate diet", 12),
    ("very low carbohydrate diet", 12),
    ("carbohydrate-restricted diet", 12),
    ("carbohydrate restricted diet", 12),
    ("ketogenic diet", 12),
    ("planetary health diet", 12),
    ("eat-lancet", 12),
    ("sustainable healthy diets", 12),
    ("sustainable healthy diet", 10),
    ("healthy sustainable diets", 12),
    ("healthy sustainable diet", 10),
    ("healthy and sustainable diets", 12),
    ("healthy and sustainable diet", 10),
    ("sustainable dietary patterns", 12),
    ("sustainable dietary pattern", 10),
    ("sustainable diets", 10),
    ("sustainable diet", 8),
    ("ultra-processed foods", 12),
    ("ultra processed foods", 12),
    ("ultra-processed food", 12),
    ("ultra processed food", 12),
    ("nova food classification", 10),
    ("nova classification", 10),
    ("meal planning", 12),
    ("commensality", 12),
    ("shared meals", 10),
    ("family meals", 10),
    ("social eating", 10),
    ("eat together", 10),
    ("self-efficacy", 10),
    ("self efficacy", 10),
    ("personalized nutrition", 12),
    ("personalised nutrition", 12),
    ("precision nutrition", 12),
    ("tailored nutrition", 12),
    ("tailored dietary advice", 12),
    ("tailored dietary intervention", 12),
    ("personalized dietary advice", 12),
    ("personalised dietary advice", 12),
    ("personalized dietary intervention", 12),
    ("personalised dietary intervention", 12),
    ("personalized meal planning", 12),
    ("personalised meal planning", 12),
    ("individualized diet", 12),
    ("individualised diet", 12),
    ("individualized dietary intervention", 12),
    ("individualised dietary intervention", 12),
    ("individualized meal plan", 12),
    ("individualised meal plan", 12),
    ("diet personalization", 12),
    ("diet personalisation", 12),
    ("abdominal obesity", 12),
    ("central obesity", 12),
    ("visceral adiposity", 12),
    ("visceral fat", 12),
    ("body mass index", 10),
    ("bmi", 10),
    ("waist circumference", 10),
    ("waist-to-height ratio", 10),
    ("waist to height ratio", 10),
    ("waist-to-hip ratio", 10),
    ("waist to hip ratio", 10),
    ("cardiometabolic health", 10),
    ("cardiometabolic", 10),
    ("metabolic health", 10),
    ("weight management", 10),
    ("adiposity", 10),
    ("type 2 diabetes remission", 16),
    ("diabetes remission", 16),
    ("remission of type 2 diabetes", 16),
    ("type 2 diabetes", 10),
    ("prediabetes", 10),
    ("diabetes", 10),
    ("metabolic syndrome", 10),
    ("hypertension", 10),
    ("blood pressure", 10),
    ("cardiovascular disease", 10),
    ("coronary artery disease", 10),
    ("atherosclerotic cardiovascular disease", 12),
    ("ascvd", 12),
    ("dyslipidaemia", 10),
    ("dyslipidemia", 10),
    ("hyperlipidaemia", 10),
    ("hyperlipidemia", 10),
    ("hypercholesterolaemia", 10),
    ("hypercholesterolemia", 10),
    ("hypertriglyceridaemia", 10),
    ("hypertriglyceridemia", 10),
    ("apolipoprotein b", 10),
    ("apo b", 10),
    ("remnant cholesterol", 10),
    ("triglyceride-rich lipoprotein", 10),
    ("triglyceride rich lipoprotein", 10),
    ("insulin resistance", 10),
    ("steatotic liver disease", 12),
    ("metabolic dysfunction-associated steatotic liver disease", 12),
    ("metabolic dysfunction associated steatotic liver disease", 12),
    ("metabolic dysfunction-associated fatty liver disease", 12),
    ("metabolic dysfunction associated fatty liver disease", 12),
    ("metabolic dysfunction-associated steatohepatitis", 12),
    ("metabolic dysfunction associated steatohepatitis", 12),
    ("hepatic steatosis", 12),
    ("fatty liver", 12),
    ("non-alcoholic fatty liver disease", 12),
    ("nonalcoholic fatty liver disease", 12),
    ("non-alcoholic steatohepatitis", 12),
    ("nonalcoholic steatohepatitis", 12),
    ("masld", 10),
    ("nafld", 10),
    ("mafld", 10),
    ("mash", 10),
    ("nash", 10),
    ("obesity", 10),
)

PENALTY_TERMS: tuple[tuple[str, float], ...] = (
    ("editorial", -40),
    ("commentary", -35),
    ("letter", -30),
    ("case report", -30),
    ("animal", -30),
    ("animal model", -35),
    ("mouse model", -35),
    ("rat model", -35),
    ("mice", -35),
    ("rodent", -35),
    ("veterinary", -35),
    ("in vitro", -30),
    ("cell culture", -30),
    ("pediatric", -15),
    ("child", -15),
    ("adolescent", -15),
    ("login", -30),
    ("buy", -30),
    ("paywall", -30),
    ("mostdownload", -30),
)

PROVIDER_BONUS = {
    "official_sources": 20,
    "pubmed": 8,
    "europepmc": 8,
    "openalex": 6,
    "crossref": 5,
}

NUTMEV_SCOPE_TERMS = (
    "nutrition",
    "diet",
    "dietary",
    "food",
    "meal",
    "culinary",
    "culinary nutrition",
    "culinary medicine program",
    "culinary medicine programme",
    "culinary medicine curriculum",
    "cooking",
    "cooking skills",
    "cooking confidence",
    "cooking self-efficacy",
    "cooking self efficacy",
    "food skills",
    "meal preparation",
    "meal preparation skills",
    "food preparation skills",
    "food preparation confidence",
    "grocery shopping skills",
    "food resource management",
    "food label literacy",
    "teaching kitchen program",
    "teaching kitchen programme",
    "lifestyle medicine",
    "lifestyle intervention",
    "lifestyle modification",
    "therapeutic lifestyle",
    "medical nutrition therapy",
    "medical nutrition therapy guideline",
    "medical nutrition therapy consensus",
    "nutrition care",
    "nutrition care pathway",
    "nutrition care pathway guideline",
    "nutrition care protocol",
    "nutrition care protocol guideline",
    "nutrition care consensus",
    "nutrition prescription",
    "nutrition prescriptions",
    "diet prescription",
    "diet prescriptions",
    "dietary prescription",
    "dietary prescriptions",
    "nutrition counseling",
    "nutrition counselling",
    "dietary counseling",
    "dietary counselling",
    "registered dietitian",
    "registered dietitian nutritionist",
    "dietitian",
    "dietitian-led intervention",
    "dietitian led intervention",
    "dietitian-led remission",
    "dietitian led remission",
    "dietitian-delivered intervention",
    "dietitian delivered intervention",
    "dietitian-managed intervention",
    "dietitian managed intervention",
    "obesity",
    "overweight",
    "adiposity",
    "body mass index",
    "bmi",
    "cardiometabolic",
    "metabolic syndrome",
    "type 2 diabetes",
    "diabetes",
    "diabetes remission",
    "type 2 diabetes remission",
    "remission of type 2 diabetes",
    "diabetes reversal",
    "glycemic remission",
    "glycaemic remission",
    "nutrition care for diabetes remission",
    "nutrition care for weight maintenance",
    "weight regain prevention",
    "weight regain management",
    "weight regain",
    "weight maintenance",
    "weight loss maintenance",
    "behavioral maintenance",
    "behavioral maintenance intervention",
    "dietary maintenance",
    "dietary maintenance intervention",
    "relapse prevention",
    "lapse management",
    "dietary self-monitoring",
    "dietary self-regulation",
    "long-term weight loss maintenance",
    "long term weight loss maintenance",
    "prediabetes",
    "insulin resistance",
    "hypertension",
    "blood pressure",
    "dyslipidemia",
    "dyslipidaemia",
    "hyperlipidemia",
    "hyperlipidaemia",
    "hypertriglyceridemia",
    "hypertriglyceridaemia",
    "apolipoprotein b",
    "apo b",
    "masld",
    "nafld",
    "mafld",
    "mash",
    "nash",
    "fatty liver",
    "steatotic liver disease",
    "hepatic steatosis",
    "mediterranean",
    "dash",
    "dietary approaches to stop hypertension",
    "mind diet",
    "plant-based",
    "plant based",
    "vegetarian",
    "vegan",
    "portfolio diet",
    "nordic diet",
    "eat-lancet",
    "planetary health diet",
    "ultra-processed",
    "ultra processed",
    "personalized nutrition",
    "personalised nutrition",
    "precision nutrition",
    "tailored nutrition",
    "tailored dietary advice",
    "tailored dietary intervention",
    "personalized dietary advice",
    "personalised dietary advice",
    "personalized dietary intervention",
    "personalised dietary intervention",
    "personalized meal planning",
    "personalised meal planning",
    "individualized diet",
    "individualised diet",
    "individualized dietary intervention",
    "individualised dietary intervention",
    "individualized meal plan",
    "individualised meal plan",
    "diet personalization",
    "diet personalisation",
    "food literacy",
    "nutrition literacy",
    "food agency",
    "food environment",
    "commensality",
    "shared meals",
    "family meals",
    "food is medicine",
    "food as medicine",
    "produce prescription",
    "medically tailored",
    "nutrition security",
    "nutrition insecurity",
    "food insecurity",
    "social prescribing",
    "screening and referral",
    "closed-loop referral",
    "closed loop referral",
    "implementation",
    "adherence",
    "behavior change",
    "behaviour change",
    "self-efficacy",
    "self efficacy",
    "motivational interviewing",
    "health coaching",
)

OUT_OF_SCOPE_HIGH_SCORE_PENALTY = -45.0


def _build_scoring_text(item: dict) -> str:
    return " ".join(str(item.get(field, "") or "") for field in SCORING_FIELDS).lower()


def _apply_terms(score: float, text: str, terms: Iterable[tuple[str, float]]) -> float:
    for key, value in terms:
        if key in text:
            score += value
    return score


def _has_nutmev_scope_signal(text: str) -> bool:
    return any(term in text for term in NUTMEV_SCOPE_TERMS)


def _is_synthetic_fallback(item: dict, text: str) -> bool:
    url = str(item.get("url") or item.get("final_url") or "").lower()
    provider = str(item.get("source_provider") or "").lower()
    return bool(item.get("fallback_used")) or "fallback.local" in url or provider == "watch_seed" or "global watch fallback item" in text


def score_watch_item(item: dict) -> float:
    text = _build_scoring_text(item)
    score = float(item.get("relevance_score") or 0)

    score = _apply_terms(score, text, BONUS_TERMS)

    if item.get("is_new"):
        score += 15
    if item.get("download_status") == "pdf":
        score += 10
    elif item.get("download_status") == "html_snapshot":
        score += 5

    provider = (item.get("source_provider") or "").lower()
    score += PROVIDER_BONUS.get(provider, 0)
    score = _apply_terms(score, text, PENALTY_TERMS)

    if not _has_nutmev_scope_signal(text):
        score += OUT_OF_SCOPE_HIGH_SCORE_PENALTY

    if not (item.get("title") or "").strip():
        score -= 20

    if _is_synthetic_fallback(item, text):
        score = min(score, 5.0)

    return round(score, 3)
