from __future__ import annotations

WATCH_CATEGORIES = {
    "guidelines_consensus": [
        "guideline",
        "clinical practice guideline",
        "consensus statement",
        "scientific statement",
        "position paper",
        "guidance statement",
        "standards of medical care in diabetes",
        "consensus",
        "consensus report",
        "consensus guidance",
        "joint guideline",
        "clinical decision pathway",
        "best practice advice",
        "practice guidance",
        "practice advisory",
        "joint statement",
        "position statement",
        "clinical guidance",
        "recommendation",
        "guideline update",
        "standards of care",
        "scientific advisory",
        "clinical pathway",
        "care pathway",
        "decision pathway",
        "living guideline",
        "food-based dietary guidelines",
        "dietary guidelines",
        "diretriz",
        "consenso",
        "declaracao cientifica",
        "recomendacoes",
    ],
    "lifestyle_medicine": [
        "lifestyle medicine",
        "lifestyle intervention",
        "lifestyle modification",
        "therapeutic lifestyle changes",
        "lifestyle medicine nutrition",
        "medical nutrition therapy",
        "food is medicine",
        "food as medicine",
        "food as medicine intervention",
        "produce prescription",
        "produce prescriptions",
        "produce rx",
        "fruit and vegetable prescription",
        "healthy food prescription",
        "food prescription program",
        "medically tailored meal",
        "medically tailored meals",
        "medically tailored grocery",
        "medically tailored groceries",
        "nutrition counseling",
        "nutrition counselling",
        "nutrition care",
        "culinary medicine",
        "culinary nutrition",
        "food literacy",
        "teaching kitchen",
        "teaching kitchens",
        "meal planning",
        "healthy lifestyle",
        "lifestyle counseling",
        "lifestyle counselling",
        "registered dietitian",
        "registered dietitian nutritionist",
        "dietitian-led",
        "dietitian led",
        "medicina do estilo de vida",
        "estilo de vida saudavel",
    ],
    "obesity_cardiometabolic": [
        "obesity",
        "clinical obesity",
        "overweight",
        "cardiometabolic risk",
        "metabolic syndrome",
        "type 2 diabetes",
        "hypertension",
        "dyslipidemia",
        "dyslipidaemia",
        "hyperlipidemia",
        "hyperlipidaemia",
        "hypercholesterolemia",
        "hypercholesterolaemia",
        "hypertriglyceridemia",
        "hypertriglyceridaemia",
        "insulin resistance",
        "prediabetes",
        "cardiovascular disease",
        "coronary artery disease",
        "MASLD",
        "NAFLD",
        "MAFLD",
        "MASH",
        "NASH",
        "fatty liver",
        "steatotic liver disease",
        "metabolic dysfunction-associated steatotic liver disease",
        "metabolic dysfunction associated steatotic liver disease",
        "metabolic dysfunction-associated fatty liver disease",
        "metabolic dysfunction associated fatty liver disease",
        "nonalcoholic fatty liver disease",
        "non-alcoholic fatty liver disease",
        "nonalcoholic steatohepatitis",
        "non-alcoholic steatohepatitis",
    ],
    "diet_patterns": [
        "Mediterranean diet",
        "DASH",
        "MIND diet",
        "Portfolio diet",
        "Nordic diet",
        "plant-based diet",
        "vegetarian diet",
        "vegan diet",
        "whole-food plant-based",
        "whole food plant based",
        "low-carb diet",
        "ketogenic diet",
        "Eat-Lancet",
        "planetary health diet",
    ],
    "implementation_behavior": [
        "adherence",
        "dietary adherence",
        "implementation science",
        "implementation research",
        "implementation framework",
        "implementation outcomes",
        "implementation fidelity",
        "implementation trial",
        "implementation evaluation",
        "hybrid effectiveness-implementation",
        "hybrid type 1",
        "hybrid type 2",
        "hybrid type 3",
        "CFIR",
        "RE-AIM",
        "implementation",
        "compliance",
        "implementation strategy",
        "implementation facilitation",
        "implementation support",
        "implementation determinant",
        "implementation determinants",
        "implementation barrier",
        "implementation barriers",
        "implementation facilitator",
        "implementation facilitators",
        "practice facilitation",
        "process evaluation",
        "knowledge translation",
        "quality improvement",
        "quality improvement study",
        "program implementation",
        "feasibility",
        "acceptability",
        "behavior change",
        "behavior change technique",
        "behavioral lifestyle intervention",
        "behavioral weight loss",
        "self-monitoring",
        "self-efficacy",
        "self-management support",
        "treatment adherence",
        "motivational interviewing",
        "goal setting",
        "food agency",
        "food is medicine",
        "food as medicine",
        "food as medicine intervention",
        "produce prescription",
        "produce prescriptions",
        "produce rx",
        "fruit and vegetable prescription",
        "healthy food prescription",
        "food prescription program",
        "medically tailored meal",
        "medically tailored meals",
        "medically tailored grocery",
        "medically tailored groceries",
        "social support",
        "shared decision making",
        "registered dietitian",
        "registered dietitian nutritionist",
        "dietitian-led intervention",
        "dietitian led intervention",
        "teaching kitchen",
        "teaching kitchens",
        "barriers and facilitators",
        "lifestyle counseling",
        "lifestyle counselling",
        "dietary counselling",
        "health coaching",
        "sustainability",
        "dissemination",
        "scale-up",
        "scale out",
        "scale-out",
        "adoption",
        "reach",
        "real-world implementation",
        "real world implementation",
        "real-world evidence",
        "real world evidence",
        "network meta-analysis",
        "umbrella review",
        "overview of reviews",
        "review of reviews",
    ],
    "food_literacy_culinary_commensality": [
        "food literacy",
        "food and nutrition literacy",
        "nutrition literacy",
        "culinary medicine",
        "food agency",
        "food label",
        "nutrition label",
        "label reading",
        "front-of-pack",
        "front-of-pack labeling",
        "front-of-pack labelling",
        "health literacy",
        "cooking skills",
        "meal planning",
        "home cooking",
        "food skills",
        "food environment",
        "food access",
        "nutrition education",
        "commensality",
        "shared meals",
        "family meals",
        "social eating",
        "eat together",
    ],
    "frameworks_instruments": [
        "framework",
        "questionnaire",
        "instrument",
        "psychometric validation",
        "psychometric study",
        "scale development",
        "questionnaire validation",
        "validation study",
        "survey instrument",
        "adherence scale",
        "food literacy instrument",
        "culinary skills instrument",
        "behavior change framework",
        "lifestyle medicine competencies",
    ],
}

MODE_LIMITS = {"quick": 3, "thesis": 6, "exhaustive": 10}
