from __future__ import annotations


def _build_scoring_text(item: dict) -> str:
    return " ".join(
        str(item.get(field, "") or "")
        for field in (
            "title",
            "abstract",
            "snippet",
            "evidence_type",
            "category",
        )
    ).lower()


def score_watch_item(item: dict) -> float:
    text = _build_scoring_text(item)
    score = float(item.get("relevance_score") or 0)

    bonus = [
        ("standards of medical care in diabetes", 60),
        ("clinical practice guideline", 60),
        ("practice guideline", 55),
        ("guideline update", 60),
        ("living guideline", 55),
        ("guideline", 50),
        ("food-based dietary guideline", 45),
        ("food guide", 40),
        ("nutrition guideline", 40),
        ("scientific statement", 45),
        ("scientific advisory", 45),
        ("consensus", 45),
        ("consensus report", 45),
        ("consensus guidance", 45),
        ("expert consensus", 45),
        ("practice advisory", 45),
        ("practice guidance", 42),
        ("guidance statement", 42),
        ("joint statement", 40),
        ("joint guideline", 42),
        ("position statement", 40),
        ("position paper", 40),
        ("clinical guidance", 40),
        ("practice recommendation", 40),
        ("best practice advice", 40),
        ("standards of care", 45),
        ("clinical pathway", 40),
        ("care pathway", 35),
        ("clinical decision pathway", 40),
        ("decision pathway", 35),
        ("systematic review", 35),
        ("living systematic review", 35),
        ("meta-analysis", 35),
        ("meta analysis", 35),
        ("network meta-analysis", 35),
        ("network meta analysis", 35),
        ("umbrella review", 35),
        ("overview of reviews", 35),
        ("review of reviews", 35),
        ("rapid review", 30),
        ("randomized trial", 30),
        ("randomised trial", 30),
        ("pragmatic trial", 30),
        ("official report", 25),
        ("questionnaire validation", 20),
        ("psychometric", 20),
        ("scale development", 18),
        ("survey instrument", 18),
        ("food literacy", 15),
        ("food and nutrition literacy", 15),
        ("nutrition literacy", 15),
        ("culinary medicine", 15),
        ("culinary nutrition", 15),
        ("teaching kitchen", 15),
        ("teaching kitchens", 15),
        ("food agency", 15),
        ("food budgeting", 12),
        ("food resource management", 12),
        ("shopping skills", 10),
        ("healthy grocery shopping", 10),
        ("food label literacy", 12),
        ("retail food environment", 14),
        ("healthy food access", 12),
        ("healthy food procurement", 14),
        ("menu labeling", 12),
        ("menu labelling", 12),
        ("meal context", 10),
        ("meal routine", 10),
        ("food is medicine", 18),
        ("food as medicine", 18),
        ("food as medicine intervention", 18),
        ("produce prescription", 18),
        ("produce prescriptions", 18),
        ("produce prescription program", 18),
        ("produce rx", 18),
        ("fruit and vegetable prescription", 18),
        ("healthy food prescription", 18),
        ("food prescription program", 18),
        ("healthy food incentive", 18),
        ("healthy food incentives", 18),
        ("nutrition incentive", 18),
        ("nutrition incentives", 18),
        ("produce voucher", 18),
        ("produce vouchers", 18),
        ("fruit and vegetable voucher", 18),
        ("fruit and vegetable vouchers", 18),
        ("medically tailored meal", 18),
        ("medically tailored meals", 18),
        ("medically tailored grocery", 18),
        ("medically tailored groceries", 18),
        ("medically tailored pantry", 18),
        ("medically tailored pantries", 18),
        ("medically tailored food package", 18),
        ("medically tailored food packages", 18),
        ("cooking skills", 12),
        ("food skills", 12),
        ("home cooking", 12),
        ("meal preparation", 12),
        ("cooking confidence", 12),
        ("nutrition education", 12),
        ("food label", 10),
        ("nutrition label", 10),
        ("label reading", 10),
        ("front-of-pack", 10),
        ("front-of-pack labeling", 12),
        ("front-of-pack labelling", 12),
        ("nutrition security", 12),
        ("adherence", 15),
        ("dietary adherence", 15),
        ("treatment adherence", 15),
        ("implementation", 15),
        ("implementation science", 15),
        ("implementation research", 15),
        ("implementation strategy", 15),
        ("implementation strategies", 15),
        ("implementation framework", 15),
        ("implementation frameworks", 15),
        ("implementation outcomes", 15),
        ("implementation outcomes framework", 15),
        ("proctor implementation outcomes", 15),
        ("implementation trial", 16),
        ("implementation evaluation", 14),
        ("implementation fidelity", 15),
        ("implementation facilitation", 15),
        ("implementation support", 12),
        ("implementation determinant", 12),
        ("implementation determinants", 12),
        ("implementation barrier", 12),
        ("implementation barriers", 12),
        ("implementation facilitator", 12),
        ("implementation facilitators", 12),
        ("implementation climate", 12),
        ("organizational readiness", 14),
        ("readiness for implementation", 14),
        ("acceptability", 12),
        ("appropriateness", 12),
        ("penetration", 10),
        ("sustainment", 12),
        ("hybrid effectiveness-implementation", 18),
        ("hybrid effectiveness implementation", 18),
        ("hybrid type 1", 16),
        ("hybrid type 2", 16),
        ("hybrid type 3", 16),
        ("cfir", 14),
        ("re-aim", 14),
        ("consolidated framework for implementation research", 16),
        ("normalization process theory", 14),
        ("theoretical domains framework", 14),
        ("motivational interviewing", 12),
        ("behavior change wheel", 14),
        ("behaviour change wheel", 14),
        ("com-b", 14),
        ("capability opportunity motivation behavior", 14),
        ("capability opportunity motivation behaviour", 14),
        ("intervention mapping", 14),
        ("implementation mapping", 14),
        ("process evaluation", 15),
        ("quality improvement", 10),
        ("quality improvement study", 12),
        ("program implementation", 10),
        ("scale out", 10),
        ("scale-out", 10),
        ("knowledge translation", 15),
        ("behavioral lifestyle intervention", 15),
        ("behavioral intervention", 14),
        ("behavioral weight loss", 15),
        ("dietary behavior", 12),
        ("dietary behaviour", 12),
        ("eating behavior", 12),
        ("eating behaviour", 12),
        ("eating habits", 10),
        ("food choice", 10),
        ("food choices", 10),
        ("meal pattern", 10),
        ("meal patterns", 10),
        ("therapeutic lifestyle changes", 15),
        ("intensive lifestyle intervention", 16),
        ("lifestyle program", 12),
        ("lifestyle programme", 12),
        ("time-restricted eating", 12),
        ("time restricted eating", 12),
        ("intermittent fasting", 12),
        ("diabetes prevention program", 14),
        ("self-management", 12),
        ("self management", 12),
        ("self-management support", 12),
        ("shared decision making", 12),
        ("health coaching", 12),
        ("practice facilitation", 14),
        ("weight loss maintenance", 12),
        ("healthy eating pattern", 12),
        ("diet quality", 10),
        ("dietary pattern", 10),
        ("goal setting", 12),
        ("social support", 12),
        ("food access", 12),
        ("lifestyle counseling", 12),
        ("lifestyle counselling", 12),
        ("medical nutrition therapy", 15),
        ("nutrition counseling", 12),
        ("nutrition counselling", 12),
        ("dietary counseling", 12),
        ("dietary counselling", 12),
        ("nutrition care", 10),
        ("nutrition care process", 14),
        ("nutrition care process model", 14),
        ("nutrition care pathway", 16),
        ("nutrition care pathways", 16),
        ("nutrition care protocol", 14),
        ("nutrition care protocols", 14),
        ("registered dietitian", 12),
        ("registered dietitian nutritionist", 12),
        ("dietitian-led", 12),
        ("dietitian led", 12),
        ("dietitian-delivered intervention", 16),
        ("dietitian delivered intervention", 16),
        ("dietitian-managed intervention", 16),
        ("dietitian managed intervention", 16),
        ("registered dietitian-led intervention", 18),
        ("registered dietitian led intervention", 18),
        ("registered dietitian nutritionist-led intervention", 18),
        ("registered dietitian nutritionist led intervention", 18),
        ("telehealth", 14),
        ("telemedicine", 14),
        ("digital health", 14),
        ("mobile health", 12),
        ("mhealth", 12),
        ("ehealth", 12),
        ("virtual care", 12),
        ("remote coaching", 12),
        ("remote monitoring", 12),
        ("digital therapeutics", 14),
        ("feasibility", 15),
        ("sustainability", 12),
        ("dissemination", 12),
        ("scale-up", 12),
        ("scale up", 12),
        ("adoption", 10),
        ("reach", 10),
        ("maintenance", 10),
        ("real-world implementation", 12),
        ("real world implementation", 12),
        ("real-world evidence", 12),
        ("real world evidence", 12),
        ("audit and feedback", 14),
        ("service delivery", 10),
        ("care delivery", 10),
        ("food environment", 15),
        ("behavior change technique", 12),
        ("barriers and facilitators", 12),
        ("mediterranean diet", 12),
        ("mediterranean dietary pattern", 12),
        ("dash", 12),
        ("dietary approaches to stop hypertension", 12),
        ("mind diet", 12),
        ("portfolio diet", 12),
        ("nordic diet", 12),
        ("new nordic diet", 12),
        ("plant-based", 12),
        ("plant based diet", 12),
        ("vegetarian diet", 12),
        ("vegetarian dietary pattern", 12),
        ("vegan diet", 12),
        ("vegan dietary pattern", 12),
        ("healthy plant-based diet", 12),
        ("healthy plant based diet", 12),
        ("provegetarian dietary pattern", 12),
        ("pro-vegetarian dietary pattern", 12),
        ("whole-food plant-based", 12),
        ("whole food plant based", 12),
        ("low-carb diet", 12),
        ("low-carbohydrate diet", 12),
        ("low carbohydrate diet", 12),
        ("very low carbohydrate diet", 12),
        ("very-low-carbohydrate diet", 12),
        ("carbohydrate-restricted diet", 12),
        ("carbohydrate restricted diet", 12),
        ("ketogenic diet", 12),
        ("planetary health diet", 12),
        ("eat-lancet", 12),
        ("ultra-processed food", 12),
        ("ultra processed food", 12),
        ("ultra-processed foods", 12),
        ("ultra processed foods", 12),
        ("nova classification", 10),
        ("nova food classification", 10),
        ("meal planning", 12),
        ("commensality", 12),
        ("shared meals", 10),
        ("family meals", 10),
        ("social eating", 10),
        ("eat together", 10),
        ("self-efficacy", 10),
        ("self efficacy", 10),
        ("obesity", 10),
        ("abdominal obesity", 12),
        ("central obesity", 12),
        ("visceral obesity", 12),
        ("visceral adiposity", 12),
        ("visceral fat", 12),
        ("ectopic fat", 12),
        ("waist circumference", 10),
        ("waist-to-height ratio", 10),
        ("waist to height ratio", 10),
        ("waist-to-hip ratio", 10),
        ("waist to hip ratio", 10),
        ("body mass index", 8),
        ("metabolic health", 10),
        ("hepatic steatosis", 12),
        ("cardiometabolic", 10),
        ("cardiometabolic health", 10),
        ("weight management", 10),
        ("adiposity", 10),
        ("diabetes", 10),
        ("type 2 diabetes remission", 16),
        ("diabetes remission", 16),
        ("remission of type 2 diabetes", 16),
        ("prediabetes", 10),
        ("metabolic syndrome", 10),
        ("hypertension", 10),
        ("blood pressure", 10),
        ("cardiovascular disease", 10),
        ("coronary artery disease", 10),
        ("atherosclerotic cardiovascular disease", 12),
        ("ascvd", 12),
        ("dyslipidemia", 10),
        ("dyslipidaemia", 10),
        ("hyperlipidemia", 10),
        ("hyperlipidaemia", 10),
        ("hypercholesterolemia", 10),
        ("hypercholesterolaemia", 10),
        ("hypertriglyceridemia", 10),
        ("hypertriglyceridaemia", 10),
        ("apolipoprotein b", 10),
        ("apo b", 10),
        ("remnant cholesterol", 10),
        ("triglyceride-rich lipoprotein", 10),
        ("triglyceride rich lipoprotein", 10),
        ("insulin resistance", 10),
        ("masld", 10),
        ("nafld", 10),
        ("mafld", 10),
        ("mash", 10),
        ("nash", 10),
        ("steatotic liver disease", 12),
        ("metabolic dysfunction-associated steatotic liver disease", 12),
        ("metabolic dysfunction associated steatotic liver disease", 12),
        ("metabolic dysfunction-associated fatty liver disease", 12),
        ("metabolic dysfunction associated fatty liver disease", 12),
        ("metabolic dysfunction-associated steatohepatitis", 12),
        ("metabolic dysfunction associated steatohepatitis", 12),
        ("fatty liver", 12),
        ("non-alcoholic fatty liver disease", 12),
        ("nonalcoholic fatty liver disease", 12),
        ("non-alcoholic steatohepatitis", 12),
        ("nonalcoholic steatohepatitis", 12),
    ]
    for key, value in bonus:
        if key in text:
            score += value

    if item.get("is_new"):
        score += 15
    if item.get("download_status") == "pdf":
        score += 10
    elif item.get("download_status") == "html_snapshot":
        score += 5

    provider = (item.get("source_provider") or "").lower()
    provider_bonus = {
        "official_sources": 20,
        "pubmed": 8,
        "europepmc": 8,
        "openalex": 6,
        "crossref": 5,
    }
    score += provider_bonus.get(provider, 0)

    penalties = [
        ("editorial", -40),
        ("commentary", -35),
        ("letter", -30),
        ("case report", -30),
        ("animal", -30),
        ("in vitro", -30),
        ("pediatric", -15),
        ("child", -15),
        ("adolescent", -15),
        ("login", -30),
        ("buy", -30),
        ("paywall", -30),
        ("mostdownload", -30),
    ]
    for key, value in penalties:
        if key in text:
            score += value

    if not (item.get("title") or "").strip():
        score -= 20

    return round(score, 3)
