from __future__ import annotations

from collections.abc import Iterable

from nutev.engine.ids import make_document_id
from nutev.global_watch.watch_config import MODE_LIMITS, WATCH_CATEGORIES

BASE_CONTEXT_TERMS = [
    "nutrition",
    "diet",
    "food",
    "obesity",
    "cardiometabolic",
]

EVIDENCE_SYNTHESIS_TERMS = [
    "systematic review",
    "meta-analysis",
    "meta analysis",
    "network meta-analysis",
    "network meta analysis",
    "umbrella review",
    "scoping review",
    "integrative review",
    "rapid review",
    "living systematic review",
    "overview of reviews",
    "review of reviews",
]

CATEGORY_CONTEXT_TERMS = {
    "guidelines_consensus": [
        "dietary guideline",
        "dietary pattern",
        "lifestyle medicine",
        "practice guideline",
        "position paper",
        "food-based dietary guideline",
        "food based dietary guideline",
        "dietary guidance",
        "consensus report",
        "consensus guidance",
        "practice advisory",
        "practice guidance",
        "guidance statement",
        "joint statement",
        "joint guideline",
        "expert consensus",
        "clinical guidance",
        "practice recommendation",
        "scientific advisory",
        "best practice advice",
        "food guide",
        "nutrition guideline",
        "standards of care",
        "clinical pathway",
        "care pathway",
        "clinical decision pathway",
        "decision pathway",
        "living guideline",
        *EVIDENCE_SYNTHESIS_TERMS,
    ],
    "lifestyle_medicine": [
        "food literacy",
        "food and nutrition literacy",
        "culinary medicine",
        "culinary nutrition",
        "teaching kitchen",
        "teaching kitchens",
        "meal planning",
        "healthy lifestyle",
        "lifestyle counseling",
        "lifestyle counselling",
        "behavioral lifestyle intervention",
        "behavioral intervention",
        "intensive lifestyle intervention",
        "lifestyle program",
        "lifestyle programme",
        "time-restricted eating",
        "time restricted eating",
        "intermittent fasting",
        "diabetes prevention program",
        "medical nutrition therapy",
        "food is medicine",
        "food as medicine",
        "produce prescription",
        "produce prescriptions",
        "produce rx",
        "fruit and vegetable prescription",
        "healthy food prescription",
        "food prescription program",
        "produce prescription program",
        "healthy food incentive",
        "healthy food incentives",
        "nutrition incentive",
        "nutrition incentives",
        "produce voucher",
        "produce vouchers",
        "fruit and vegetable voucher",
        "fruit and vegetable vouchers",
        "medically tailored meal",
        "medically tailored meals",
        "medically tailored grocery",
        "medically tailored groceries",
        "medically tailored pantry",
        "medically tailored pantries",
        "medically tailored food package",
        "medically tailored food packages",
        "nutrition counseling",
        "nutrition counselling",
        "nutrition care",
        "registered dietitian",
        "registered dietitian nutritionist",
        "dietitian-led",
        "dietitian led",
    ],
    "obesity_cardiometabolic": [
        "dietary pattern",
        "lifestyle medicine",
        "implementation",
        "adherence",
        "metabolic syndrome",
        "type 2 diabetes",
        "prediabetes",
        "insulin resistance",
        "hypertension",
        "cardiovascular disease",
        "coronary artery disease",
        "atherosclerotic cardiovascular disease",
        "ascvd",
        "dyslipidaemia",
        "hyperlipidemia",
        "hyperlipidaemia",
        "hypercholesterolemia",
        "hypercholesterolaemia",
        "hypertriglyceridemia",
        "hypertriglyceridaemia",
        "apolipoprotein b",
        "apo b",
        "remnant cholesterol",
        "triglyceride-rich lipoprotein",
        "triglyceride rich lipoprotein",
        "MASLD",
        "NAFLD",
        "MAFLD",
        "MASH",
        "NASH",
        "fatty liver",
        "steatotic liver disease",
        "metabolic dysfunction-associated steatotic liver disease",
        "metabolic dysfunction associated steatotic liver disease",
        "metabolic dysfunction-associated fatty liver disease",
        "metabolic dysfunction associated fatty liver disease",
        "metabolic dysfunction-associated steatohepatitis",
        "metabolic dysfunction associated steatohepatitis",
        "nonalcoholic fatty liver disease",
        "non-alcoholic fatty liver disease",
        "nonalcoholic steatohepatitis",
        "non-alcoholic steatohepatitis",
        "weight management",
        "adiposity",
        "adiposity-based chronic disease",
        "adiposity based chronic disease",
        "blood pressure",
        *EVIDENCE_SYNTHESIS_TERMS,
    ],
    "diet_patterns": [
        "type 2 diabetes",
        "hypertension",
        "implementation",
        "adherence",
        "insulin resistance",
        "steatotic liver disease",
        "mediterranean diet",
        "mediterranean dietary pattern",
        "dash",
        "dietary approaches to stop hypertension",
        "mind diet",
        "plant-based diet",
        "plant based diet",
        "vegetarian diet",
        "vegetarian dietary pattern",
        "vegan diet",
        "vegan dietary pattern",
        "healthy plant-based diet",
        "healthy plant based diet",
        "pro-vegetarian dietary pattern",
        "provegetarian dietary pattern",
        "whole-food plant-based",
        "whole food plant based",
        "low-carb diet",
        "low-carbohydrate diet",
        "low carbohydrate diet",
        "very low carbohydrate diet",
        "very-low-carbohydrate diet",
        "carbohydrate-restricted diet",
        "carbohydrate restricted diet",
        "ketogenic diet",
        "meal replacement",
        "meal replacements",
        "partial meal replacement",
        "partial meal replacements",
        "total diet replacement",
        "total diet replacements",
        "formula diet",
        "formula diets",
        "very low energy diet",
        "very-low-energy diet",
        "low energy diet",
        "low-energy diet",
        "very low calorie diet",
        "very-low-calorie diet",
        "portfolio diet",
        "nordic diet",
        "new nordic diet",
        "eat-lancet",
        "planetary health diet",
        "ultra-processed food",
        "ultra processed food",
        "ultra-processed foods",
        "ultra processed foods",
        "nova classification",
        "nova food classification",
        *EVIDENCE_SYNTHESIS_TERMS,
    ],
    "implementation_behavior": [
        "lifestyle medicine",
        "food literacy",
        "culinary medicine",
        "culinary nutrition",
        "teaching kitchen",
        "teaching kitchens",
        "implementation science",
        "implementation research",
        "knowledge translation",
        "acceptability",
        "appropriateness",
        "dietary adherence",
        "treatment adherence",
        "self-efficacy",
        "self efficacy",
        "self-monitoring",
        "self-management",
        "self management",
        "self-management support",
        "meal planning",
        "implementation strategy",
        "implementation strategies",
        "implementation framework",
        "implementation frameworks",
        "implementation outcomes",
        "implementation fidelity",
        "implementation facilitation",
        "implementation support",
        "implementation barrier",
        "implementation barriers",
        "implementation facilitator",
        "implementation facilitators",
        "implementation determinant",
        "implementation determinants",
        "implementation climate",
        "organizational readiness",
        "readiness for implementation",
        "penetration",
        "sustainment",
        "hybrid effectiveness-implementation",
        "hybrid effectiveness implementation",
        "hybrid type 1",
        "hybrid type 2",
        "hybrid type 3",
        "cfir",
        "consolidated framework for implementation research",
        "re-aim",
        "normalization process theory",
        "theoretical domains framework",
        "process evaluation",
        "shared decision making",
        "motivational interviewing",
        "behavior change technique",
        "behavior change wheel",
        "behaviour change wheel",
        "COM-B",
        "capability opportunity motivation behavior",
        "capability opportunity motivation behaviour",
        "intervention mapping",
        "implementation mapping",
        "barriers and facilitators",
        "behavioral lifestyle intervention",
        "behavioral weight loss",
        "goal setting",
        "social support",
        "food access",
        "food is medicine",
        "food as medicine",
        "produce prescription",
        "produce prescriptions",
        "produce rx",
        "fruit and vegetable prescription",
        "healthy food prescription",
        "food prescription program",
        "produce prescription program",
        "healthy food incentive",
        "healthy food incentives",
        "nutrition incentive",
        "nutrition incentives",
        "produce voucher",
        "produce vouchers",
        "fruit and vegetable voucher",
        "fruit and vegetable vouchers",
        "medically tailored meal",
        "medically tailored meals",
        "medically tailored grocery",
        "medically tailored groceries",
        "medically tailored pantry",
        "medically tailored pantries",
        "medically tailored food package",
        "medically tailored food packages",
        "nutrition care process",
        "nutrition care process model",
        "nutrition care pathway",
        "nutrition care pathways",
        "nutrition care protocol",
        "nutrition care protocols",
        "registered dietitian",
        "registered dietitian nutritionist",
        "dietitian-led",
        "dietitian led",
        "dietitian-delivered intervention",
        "dietitian delivered intervention",
        "dietitian-managed intervention",
        "dietitian managed intervention",
        "registered dietitian-led intervention",
        "registered dietitian led intervention",
        "registered dietitian nutritionist-led intervention",
        "registered dietitian nutritionist led intervention",
        "telehealth",
        "telemedicine",
        "digital health",
        "mobile health",
        "mhealth",
        "ehealth",
        "virtual care",
        "remote coaching",
        "remote monitoring",
        "digital therapeutics",
        "sustainability",
        "dissemination",
        "scale-up",
        "scale up",
        "adoption",
        "reach",
        "maintenance",
        "real-world implementation",
        "real world implementation",
        "real-world evidence",
        "real world evidence",
        "registered dietitian",
        "registered dietitian nutritionist",
        "dietitian-led",
        "dietitian led",
        "audit and feedback",
        "service delivery",
        "care delivery",
        *EVIDENCE_SYNTHESIS_TERMS,
    ],
    "food_literacy_culinary_commensality": [
        "lifestyle medicine",
        "behavior change",
        "adherence",
        "food environment",
        "nutrition education",
        "food and nutrition literacy",
        "nutrition literacy",
        "nutrition security",
        "food agency",
        "food budgeting",
        "food resource management",
        "shopping skills",
        "healthy grocery shopping",
        "food label",
        "nutrition label",
        "label reading",
        "food label literacy",
        "front-of-pack",
        "front-of-pack labeling",
        "front-of-pack labelling",
        "food policy",
        "nutrition policy",
        "home cooking",
        "meal preparation",
        "cooking confidence",
        "cooking skills",
        "food skills",
        "culinary nutrition",
        "teaching kitchen",
        "teaching kitchens",
        "food access",
        "retail food environment",
        "healthy food access",
        "healthy food procurement",
        "menu labeling",
        "menu labelling",
        "commensality",
        "shared meals",
        "family meals",
        "social eating",
        "eat together",
        "meal context",
        "meal routine",
    ],
    "frameworks_instruments": [
        "lifestyle medicine",
        "food literacy",
        "culinary medicine",
        "commensality",
        "psychometric validation",
        "scale development",
        "lifestyle medicine competencies",
    ],
}

QUICK_MODE_SEED_GROUPS = {
    "guidelines_consensus": [
        [
            "clinical practice guideline",
            "guideline",
            "guidelines",
            "guideline update",
            "dietary guidelines",
            "food-based dietary guidelines",
            "diretriz",
            "recomendações",
        ],
        [
            "consensus",
            "consensus statement",
            "consensus report",
            "consensus guidance",
            "expert consensus",
            "consenso",
            "standards of care",
        ],
        [
            "scientific statement",
            "scientific advisory",
            "position statement",
            "position paper",
            "practice advisory",
            "practice guidance",
            "best practice advice",
            "guidance statement",
            "joint statement",
            "joint guideline",
            "clinical guidance",
            "recommendation",
            "declaração científica",
            "clinical pathway",
            "care pathway",
            "clinical decision pathway",
            "decision pathway",
            "living guideline",
        ],
    ],
    "lifestyle_medicine": [
        [
            "lifestyle medicine",
            "lifestyle medicine nutrition",
            "medical nutrition therapy",
            "medicina do estilo de vida",
        ],
        [
            "lifestyle intervention",
            "lifestyle modification",
            "therapeutic lifestyle changes",
            "intensive lifestyle intervention",
            "lifestyle program",
            "lifestyle programme",
            "behavioral intervention",
            "nutrition counseling",
            "nutrition counselling",
            "food is medicine",
            "food as medicine",
            "food as medicine intervention",
            "produce prescription",
            "produce prescriptions",
            "produce rx",
            "fruit and vegetable prescription",
            "healthy food prescription",
            "food prescription program",
            "healthy food incentive",
            "produce voucher",
            "nutrition incentive",
        ],
        [
            "healthy lifestyle",
            "lifestyle counseling",
            "lifestyle counselling",
            "nutrition care",
            "culinary medicine",
            "culinary nutrition",
            "food literacy",
            "food and nutrition literacy",
            "teaching kitchen",
            "teaching kitchens",
            "meal planning",
            "time-restricted eating",
            "time restricted eating",
            "intermittent fasting",
            "diabetes prevention program",
            "registered dietitian",
            "registered dietitian nutritionist",
            "dietitian-led",
            "dietitian led",
            "estilo de vida saudavel",
            "medically tailored meal",
            "medically tailored meals",
            "medically tailored grocery",
            "medically tailored groceries",
            "medically tailored pantry",
            "medically tailored food package",
            "fruit and vegetable vouchers",
        ],
    ],
    "obesity_cardiometabolic": [
        [
            "obesity",
            "clinical obesity",
            "overweight",
            "adiposity",
            "adiposity-based chronic disease",
            "adiposity based chronic disease",
            "weight management",
        ],
        [
            "cardiometabolic risk",
            "metabolic syndrome",
            "type 2 diabetes",
            "prediabetes",
            "insulin resistance",
        ],
        [
            "hypertension",
            "dyslipidemia",
            "dyslipidaemia",
            "hyperlipidemia",
            "hyperlipidaemia",
            "hypercholesterolemia",
            "hypercholesterolaemia",
            "hypertriglyceridemia",
            "hypertriglyceridaemia",
            "apolipoprotein b",
            "apo b",
            "remnant cholesterol",
            "triglyceride-rich lipoprotein",
            "triglyceride rich lipoprotein",
            "MASLD",
            "NAFLD",
            "MAFLD",
            "MASH",
            "NASH",
            "fatty liver",
            "steatotic liver disease",
            "metabolic dysfunction-associated steatohepatitis",
            "metabolic dysfunction associated steatohepatitis",
            "metabolic dysfunction-associated steatotic liver disease",
            "metabolic dysfunction associated steatotic liver disease",
            "metabolic dysfunction-associated fatty liver disease",
            "metabolic dysfunction associated fatty liver disease",
            "nonalcoholic fatty liver disease",
            "non-alcoholic fatty liver disease",
            "nonalcoholic steatohepatitis",
            "non-alcoholic steatohepatitis",
            "systematic review",
            "meta-analysis",
            "umbrella review",
        ],
    ],
    "diet_patterns": [
        [
            "Mediterranean diet",
            "Mediterranean dietary pattern",
            "DASH",
            "Dietary Approaches to Stop Hypertension",
            "MIND diet",
        ],
        [
            "plant-based diet",
            "plant based diet",
            "vegetarian diet",
            "vegetarian dietary pattern",
            "vegan diet",
            "vegan dietary pattern",
            "healthy plant-based diet",
            "healthy plant based diet",
            "provegetarian dietary pattern",
            "whole-food plant-based",
            "whole food plant based",
            "low-carb diet",
            "low-carbohydrate diet",
            "low carbohydrate diet",
            "very low carbohydrate diet",
            "very-low-carbohydrate diet",
            "carbohydrate-restricted diet",
            "carbohydrate restricted diet",
            "ketogenic diet",
        ],
        [
            "Eat-Lancet",
            "planetary health diet",
            "Portfolio diet",
            "Nordic diet",
            "New Nordic diet",
            "meal replacement",
            "meal replacements",
            "partial meal replacement",
            "partial meal replacements",
            "total diet replacement",
            "total diet replacements",
            "formula diet",
            "formula diets",
            "very low energy diet",
            "very-low-energy diet",
            "low energy diet",
            "low-energy diet",
            "very low calorie diet",
            "very-low-calorie diet",
            "ultra-processed food",
            "ultra processed food",
            "NOVA classification",
            "systematic review",
            "network meta-analysis",
            "umbrella review",
            "rapid review",
            "living systematic review",
        ],
    ],
    "implementation_behavior": [
        [
            "adherence",
            "compliance",
            "acceptability",
            "appropriateness",
            "feasibility",
            "self-monitoring",
            "self-efficacy",
            "self efficacy",
            "dietary adherence",
            "treatment adherence",
            "self-management",
            "maintenance",
            "weight loss maintenance",
        ],
        [
            "implementation",
            "implementation science",
            "implementation research",
            "implementation framework",
            "implementation frameworks",
            "implementation fidelity",
            "implementation facilitation",
            "implementation support",
            "implementation outcomes",
            "implementation determinants",
            "implementation barriers",
            "implementation facilitators",
            "implementation climate",
            "organizational readiness",
            "readiness for implementation",
            "penetration",
            "hybrid effectiveness-implementation",
            "hybrid effectiveness implementation",
            "hybrid type 1",
            "hybrid type 2",
            "hybrid type 3",
            "process evaluation",
            "practice facilitation",
            "health coaching",
            "RE-AIM",
            "CFIR",
            "consolidated framework for implementation research",
            "normalization process theory",
            "theoretical domains framework",
            "barriers and facilitators",
            "lifestyle counseling",
            "lifestyle counselling",
            "self-management support",
            "shared decision making",
            "implementation strategy",
            "implementation strategies",
            "nutrition care process",
            "nutrition care process model",
            "nutrition care pathway",
            "nutrition care pathways",
            "nutrition care protocol",
            "nutrition care protocols",
            "dietitian-delivered intervention",
            "dietitian delivered intervention",
            "dietitian-managed intervention",
            "dietitian managed intervention",
            "registered dietitian-led intervention",
            "registered dietitian led intervention",
            "registered dietitian nutritionist-led intervention",
            "registered dietitian nutritionist led intervention",
        ],
        [
            "behavior change",
            "behavior change technique",
            "behavior change wheel",
            "behaviour change wheel",
            "COM-B",
            "capability opportunity motivation behavior",
            "capability opportunity motivation behaviour",
            "motivational interviewing",
            "intervention mapping",
            "implementation mapping",
            "action planning",
            "coping planning",
            "self-regulation",
            "self regulation",
            "stages of change",
            "stage of change",
            "readiness to change",
            "transtheoretical model",
            "social support",
            "food agency",
            "meal planning",
            "registered dietitian",
            "registered dietitian nutritionist",
            "dietitian-led intervention",
            "dietitian led intervention",
            "teaching kitchen",
            "teaching kitchens",
            "culinary nutrition",
            "food is medicine",
            "food as medicine",
            "produce prescription",
            "produce prescriptions",
            "produce rx",
            "fruit and vegetable prescription",
            "healthy food prescription",
            "food prescription program",
            "medically tailored meals",
            "medically tailored groceries",
            "healthy food incentive",
            "nutrition incentive",
            "produce vouchers",
            "fruit and vegetable voucher",
            "medically tailored pantry",
            "medically tailored food package",
            "telehealth",
            "telemedicine",
            "digital health",
            "mobile health",
            "mhealth",
            "ehealth",
            "virtual care",
            "remote coaching",
            "remote monitoring",
            "digital therapeutics",
            "sustainment",
            "sustainability",
            "dissemination",
            "scale-up",
            "adoption",
            "reach",
            "real-world implementation",
            "real world implementation",
            "real-world evidence",
            "real world evidence",
            "systematic review",
            "scoping review",
            "rapid review",
            "audit and feedback",
            "service delivery",
            "care delivery",
        ],
    ],
    "food_literacy_culinary_commensality": [
        [
            "food literacy",
            "food and nutrition literacy",
            "nutrition literacy",
            "health literacy",
            "nutrition security",
        ],
        [
            "culinary medicine",
            "culinary nutrition",
            "teaching kitchen",
            "teaching kitchens",
            "cooking skills",
            "food skills",
            "food agency",
            "home cooking",
            "meal planning",
            "meal preparation",
            "cooking confidence",
            "food budgeting",
            "food resource management",
            "shopping skills",
            "healthy grocery shopping",
            "food label literacy",
        ],
        [
            "food environment",
            "food access",
            "retail food environment",
            "healthy food access",
            "healthy food procurement",
            "shared meals",
            "family meals",
            "social eating",
            "eat together",
            "commensality",
            "comensalidade",
            "menu labeling",
            "menu labelling",
            "meal context",
            "meal routine",
            "food policy",
            "nutrition policy",
            "food label",
            "nutrition label",
            "label reading",
            "front-of-pack",
            "front-of-pack labeling",
            "front-of-pack labelling",
        ],
    ],
    "frameworks_instruments": [
        [
            "framework",
            "behavior change framework",
            "lifestyle medicine competencies",
        ],
        [
            "questionnaire",
            "instrument",
            "survey instrument",
            "adherence scale",
            "food literacy instrument",
            "culinary skills instrument",
        ],
        [
            "psychometric validation",
            "psychometric study",
            "scale development",
            "questionnaire validation",
            "validation study",
        ],
    ],
}

THESIS_MODE_SEED_GROUPS = {
    "lifestyle_medicine": [
        [
            "lifestyle medicine",
            "lifestyle medicine nutrition",
            "medical nutrition therapy",
            "medicina do estilo de vida",
        ],
        [
            "lifestyle intervention",
            "lifestyle modification",
            "therapeutic lifestyle changes",
            "intensive lifestyle intervention",
            "lifestyle program",
            "lifestyle programme",
        ],
        [
            "food is medicine",
            "food as medicine",
            "food as medicine intervention",
            "produce prescription",
            "produce prescriptions",
            "produce rx",
        ],
        [
            "culinary medicine",
            "culinary nutrition",
            "food literacy",
            "food and nutrition literacy",
            "teaching kitchen",
            "teaching kitchens",
        ],
        [
            "registered dietitian",
            "registered dietitian nutritionist",
            "dietitian-led",
            "dietitian led",
            "nutrition counseling",
            "nutrition counselling",
        ],
        [
            "time-restricted eating",
            "time restricted eating",
            "intermittent fasting",
            "diabetes prevention program",
            "meal planning",
            "healthy lifestyle",
        ],
    ],
    "implementation_behavior": [
        [
            "adherence",
            "dietary adherence",
            "treatment adherence",
            "acceptability",
            "appropriateness",
            "feasibility",
            "self-efficacy",
            "self efficacy",
            "self-management support",
        ],
        [
            "implementation science",
            "implementation research",
            "implementation framework",
            "implementation frameworks",
            "implementation outcomes",
            "implementation strategy",
            "implementation strategies",
            "process evaluation",
            "knowledge translation",
            "nutrition care process",
            "nutrition care process model",
            "nutrition care pathway",
            "nutrition care pathways",
            "nutrition care protocol",
            "nutrition care protocols",
            "dietitian-delivered intervention",
            "dietitian delivered intervention",
            "dietitian-managed intervention",
            "dietitian managed intervention",
            "registered dietitian-led intervention",
            "registered dietitian led intervention",
            "registered dietitian nutritionist-led intervention",
            "registered dietitian nutritionist led intervention",
        ],
        [
            "behavior change",
            "behavior change technique",
            "behavior change wheel",
            "behaviour change wheel",
            "COM-B",
            "capability opportunity motivation behavior",
            "capability opportunity motivation behaviour",
            "motivational interviewing",
            "goal setting",
            "action planning",
            "coping planning",
            "self-regulation",
            "self regulation",
            "stages of change",
            "stage of change",
            "readiness to change",
            "transtheoretical model",
        ],
        [
            "digital health",
            "telehealth",
            "telemedicine",
            "mobile health",
            "mhealth",
            "ehealth",
            "virtual care",
            "remote coaching",
            "remote monitoring",
            "digital therapeutics",
        ],
        [
            "food is medicine",
            "food as medicine",
            "produce prescription",
            "produce prescriptions",
            "produce rx",
            "fruit and vegetable prescription",
            "healthy food prescription",
            "food prescription program",
            "medically tailored meals",
            "medically tailored groceries",
            "healthy food incentives",
            "nutrition incentives",
            "produce voucher",
            "fruit and vegetable vouchers",
            "medically tailored pantry",
            "medically tailored food packages",
        ],
        [
            "registered dietitian",
            "registered dietitian nutritionist",
            "dietitian-led intervention",
            "dietitian led intervention",
            "teaching kitchen",
            "teaching kitchens",
            "health coaching",
            "shared decision making",
            "social support",
        ],
    ],
}

EXHAUSTIVE_MODE_SEED_GROUPS = {
    "lifestyle_medicine": [
        [
            "lifestyle medicine",
            "lifestyle medicine nutrition",
            "medical nutrition therapy",
            "medicina do estilo de vida",
        ],
        [
            "lifestyle intervention",
            "lifestyle modification",
            "therapeutic lifestyle changes",
            "intensive lifestyle intervention",
        ],
        [
            "behavioral lifestyle intervention",
            "behavioral intervention",
            "lifestyle program",
            "lifestyle programme",
        ],
        [
            "food is medicine",
            "food as medicine",
            "food as medicine intervention",
            "produce prescription",
        ],
        [
            "produce prescriptions",
            "produce rx",
            "fruit and vegetable prescription",
            "healthy food prescription",
        ],
        [
            "medically tailored meal",
            "medically tailored meals",
            "medically tailored grocery",
            "medically tailored groceries",
        ],
        [
            "culinary medicine",
            "culinary nutrition",
            "teaching kitchen",
            "teaching kitchens",
        ],
        [
            "food literacy",
            "food and nutrition literacy",
            "meal planning",
            "nutrition care",
        ],
        [
            "registered dietitian",
            "registered dietitian nutritionist",
            "dietitian-led",
            "dietitian led",
        ],
        [
            "time-restricted eating",
            "time restricted eating",
            "intermittent fasting",
            "diabetes prevention program",
        ],
    ],
}

HIGH_PRIORITY_MARKERS = (
    "guideline",
    "consensus",
    "statement",
    "recommendation",
    "position paper",
    "standards of care",
    "clinical pathway",
    "care pathway",
    "clinical decision pathway",
    "decision pathway",
)


def _dedupe_terms(terms: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    unique_terms: list[str] = []
    for term in terms:
        value = str(term).strip()
        if not value:
            continue
        lowered = value.lower()
        if lowered in seen:
            continue
        seen.add(lowered)
        unique_terms.append(value)
    return unique_terms


def _quote_term(term: str) -> str:
    return f'"{term.strip()}"'


def _or_clause(terms: Iterable[str]) -> str:
    quoted_terms = [_quote_term(term) for term in _dedupe_terms(terms)]
    if not quoted_terms:
        return ""
    if len(quoted_terms) == 1:
        return quoted_terms[0]
    return "(" + " OR ".join(quoted_terms) + ")"


def _build_context_terms(category: str) -> list[str]:
    return _dedupe_terms(
        [
            *BASE_CONTEXT_TERMS,
            *CATEGORY_CONTEXT_TERMS.get(category, []),
        ]
    )


def _priority_for_term(term: str | Iterable[str]) -> int:
    candidates = [term] if isinstance(term, str) else list(term)
    lowered_candidates = [str(value).lower() for value in candidates]
    if any(
        marker in candidate
        for candidate in lowered_candidates
        for marker in HIGH_PRIORITY_MARKERS
    ):
        return 1
    return 2


def _mode_terms(category: str, mode: str) -> list[str | list[str]]:
    if mode == "quick" and category in QUICK_MODE_SEED_GROUPS:
        return QUICK_MODE_SEED_GROUPS[category]
    if mode == "thesis" and category in THESIS_MODE_SEED_GROUPS:
        return THESIS_MODE_SEED_GROUPS[category]
    if mode == "exhaustive" and category in EXHAUSTIVE_MODE_SEED_GROUPS:
        return EXHAUSTIVE_MODE_SEED_GROUPS[category]
    return WATCH_CATEGORIES.get(category, [])


def _term_clause(term: str | Iterable[str]) -> str:
    if isinstance(term, str):
        return _quote_term(term)
    return _or_clause(term)


def _build_category_queries(
    category: str,
    since_days: int,
    mode: str,
) -> list[dict[str, object]]:
    context_clause = _or_clause(_build_context_terms(category))
    ranked_queries: list[tuple[int, dict[str, object]]] = []
    for index, term in enumerate(
        _mode_terms(category, mode)[: MODE_LIMITS.get(mode, 6)]
    ):
        term_clause = _term_clause(term)
        query = f"({term_clause})"
        if context_clause:
            query = f"{query} AND {context_clause}"
        ranked_queries.append(
            (
                index,
                {
                    "query_id": make_document_id(
                        {"title": query, "provider": "watch", "year": since_days}
                    ),
                    "category": category,
                    "query": query,
                    "provider_hint": "pubmed",
                    "priority": 2 if category == "implementation_behavior" else _priority_for_term(term),
                    "since_days": since_days,
                },
            )
        )
    if category == "implementation_behavior":
        return [query for _, query in ranked_queries]
    return [
        query
        for _, query in sorted(
            ranked_queries,
            key=lambda item: (int(item[1]["priority"]), item[0]),
        )
    ]


def _interleave_category_queries(
    category_queries: dict[str, list[dict[str, object]]],
) -> list[dict[str, object]]:
    ordered: list[dict[str, object]] = []
    max_bucket = max((len(bucket) for bucket in category_queries.values()), default=0)
    for index in range(max_bucket):
        for category in category_queries:
            bucket = category_queries.get(category, [])
            if index < len(bucket):
                ordered.append(bucket[index])
    return ordered


def build_watch_queries(
    categories: list[str] | None,
    since_days: int,
    mode: str,
) -> list[dict[str, object]]:
    selected_categories = categories or list(WATCH_CATEGORIES.keys())
    category_queries = {
        category: _build_category_queries(category, since_days, mode)
        for category in selected_categories
    }
    return _interleave_category_queries(category_queries)
