from __future__ import annotations

WORKSTREAM_ALIASES = {
    "a3": "artigo3_framework",
    "article3": "artigo3_framework",
}

SemanticBlock = dict[str, list[str]]

SEMANTIC_RESEARCH_BLOCKS: dict[str, SemanticBlock] = {
    "implementation_science": {
        "terms": [
            "implementation science",
            "implementation research",
            "implementation strategy",
            "implementation outcomes",
            "implementation fidelity",
            "knowledge translation",
            "implementation framework",
            "implementation frameworks",
            "implementation process",
            "implementation facilitation",
            "implementation support",
            "implementation evaluation",
            "process evaluation",
            "implementation barrier",
            "implementation barriers",
            "implementation facilitator",
            "implementation facilitators",
            "implementation determinant",
            "implementation determinants",
            "acceptability",
            "feasibility",
            "appropriateness",
            "penetration",
            "sustainment",
            "implementation climate",
            "organizational readiness",
            "readiness for implementation",
            "barriers",
            "facilitators",
            "barriers and facilitators",
            "real-world implementation",
            "real world implementation",
            "pragmatic implementation",
            "real-world evidence",
            "real world evidence",
            "adoption",
            "reach",
            "sustainability",
            "dissemination",
            "scale-up",
            "scale up",
            "scale out",
            "RE-AIM",
            "RE-AIM framework",
            "CFIR",
            "consolidated framework for implementation research",
            "normalization process theory",
            "theoretical domains framework",
            "hybrid effectiveness implementation",
            "hybrid effectiveness-implementation",
            "hybrid type 1",
            "hybrid type 2",
            "hybrid type 3",
            "implementation study",
            "implementation trial",
            "practice facilitation",
            "audit and feedback",
            "quality improvement",
            "care delivery",
            "service delivery",
            "program implementation",
            "clinical pathway",
            "care pathway",
            "shared decision making",
            "motivational interviewing",
            "behavior change technique",
            "behavior change techniques",
            "behaviour change technique",
            "behaviour change techniques",
            "behavior change taxonomy",
            "behaviour change taxonomy",
            "behavior change wheel",
            "behaviour change wheel",
            "behavior change intervention",
            "behaviour change intervention",
            "behavior change intervention functions",
            "behaviour change intervention functions",
            "capability opportunity motivation behavior",
            "capability opportunity motivation behaviour",
            "COM-B",
            "COM B",
            "intervention mapping",
            "implementation mapping",
            "implementation outcomes framework",
            "proctor implementation outcomes",
            "self-management support",
            "health coaching",
            "telehealth",
            "telemedicine",
            "digital health",
            "mobile health",
            "mhealth",
            "ehealth",
            "virtual care",
            "remote coaching",
            "remote monitoring",
            "digital therapeutics",
            "app-based",
            "app based",
            "nutrition counseling",
            "nutrition counselling",
            "registered dietitian",
            "registered dietitian nutritionist",
            "registered dietitian-led",
            "registered dietitian led",
            "registered dietitian nutritionist-led",
            "registered dietitian nutritionist led",
            "dietitian-delivered",
            "dietitian delivered",
            "dietitian-managed",
            "dietitian managed",
            "dietitian-led intervention",
            "dietitian led intervention",
            "dietitian-delivered intervention",
            "dietitian delivered intervention",
            "dietitian-managed intervention",
            "dietitian managed intervention",
            "registered dietitian-led intervention",
            "registered dietitian led intervention",
            "registered dietitian nutritionist-led intervention",
            "registered dietitian nutritionist led intervention",
            "nutrition care process",
            "nutrition care process model",
            "nutrition care pathway",
            "nutrition care pathways",
            "nutrition care protocol",
            "food is medicine intervention",
            "produce prescription program",
        ],
        "document_terms": [
            "implementation study",
            "implementation trial",
            "implementation evaluation",
            "process evaluation",
            "mixed methods study",
            "real-world evidence",
            "real world evidence",
            "dissemination study",
            "hybrid effectiveness-implementation",
            "hybrid type 1",
            "hybrid type 2",
            "hybrid type 3",
            "quality improvement study",
            "clinical pathway",
            "care pathway",
            "audit and feedback",
            "behavior change taxonomy",
            "behaviour change taxonomy",
            "behavior change wheel",
            "behaviour change wheel",
            "behavior change intervention",
            "behaviour change intervention",
            "intervention mapping",
            "implementation mapping",
            "implementation outcomes framework",
            "nutrition care process model",
            "nutrition care pathway",
            "nutrition care protocol",
            "dietitian-led intervention",
            "dietitian-delivered intervention",
            "dietitian-managed intervention",
            "registered dietitian-led intervention",
            "registered dietitian nutritionist-led intervention",
        ],
    },
    "nutrition_care_delivery": {
        "terms": [
            "medical nutrition therapy",
            "nutrition therapy",
            "diet therapy",
            "dietetic treatment",
            "dietary treatment",
            "medical nutrition therapy intervention",
            "nutrition therapy intervention",
            "diet therapy intervention",
            "registered dietitian-led",
            "registered dietitian led",
            "registered dietitian nutritionist-led",
            "registered dietitian nutritionist led",
            "dietitian-delivered",
            "dietitian delivered",
            "dietitian-managed",
            "dietitian managed",
            "dietitian-led intervention",
            "dietitian led intervention",
            "dietitian-delivered intervention",
            "dietitian delivered intervention",
            "dietitian-managed intervention",
            "dietitian managed intervention",
            "registered dietitian-led intervention",
            "registered dietitian led intervention",
            "registered dietitian nutritionist-led intervention",
            "registered dietitian nutritionist led intervention",
            "nutrition care process",
            "nutrition care process model",
            "nutrition care pathway",
            "nutrition care pathways",
            "nutrition care protocol",
            "nutrition care protocols",
            "nutrition care plan",
            "nutrition care plans",
        ],
        "document_terms": [
            "medical nutrition therapy guideline",
            "medical nutrition therapy consensus",
            "medical nutrition therapy intervention",
            "nutrition therapy guideline",
            "nutrition therapy intervention",
            "diet therapy guideline",
            "diet therapy intervention",
            "dietitian-led intervention",
            "dietitian delivered intervention",
            "dietitian-delivered intervention",
            "dietitian managed intervention",
            "dietitian-managed intervention",
            "registered dietitian-led intervention",
            "registered dietitian led intervention",
            "registered dietitian nutritionist-led intervention",
            "registered dietitian nutritionist led intervention",
            "nutrition care process model",
            "nutrition care pathway",
            "nutrition care pathways",
            "nutrition care protocol",
            "nutrition care protocols",
            "nutrition care plan",
            "nutrition care plans",
        ],
    },
    "adherence_persistence": {
        "terms": [
            "adherence",
            "dietary adherence",
            "treatment adherence",
            "long-term adherence",
            "maintenance",
            "weight maintenance",
            "weight loss maintenance",
            "long-term weight loss maintenance",
            "long term weight loss maintenance",
            "weight regain",
            "weight regain prevention",
            "weight regain management",
            "diabetes remission",
            "type 2 diabetes remission",
            "diabetes reversal",
            "glycemic remission",
            "glycaemic remission",
            "remission of type 2 diabetes",
            "diet-induced diabetes remission",
            "diet induced diabetes remission",
            "lifestyle-induced diabetes remission",
            "lifestyle induced diabetes remission",
            "remission maintenance",
            "diabetes remission maintenance",
            "dietary maintenance",
            "diet quality",
            "healthy eating index",
            "persistence",
            "engagement",
            "retention",
            "dropout",
            "attrition",
            "behavioral maintenance",
            "behavioural maintenance",
            "self-monitoring",
            "dietary self-monitoring",
            "dietary self-regulation",
            "dietary self regulation",
            "eating self-regulation",
            "self-regulation of eating",
            "self management",
            "self-management support",
            "relapse prevention",
            "lapse management",
            "dietary lapse",
            "dietary lapses",
            "habit formation",
            "action planning",
            "coping planning",
            "implementation intentions",
            "goal setting",
            "problem solving",
            "motivational interviewing",
            "health coaching",
            "health coach",
            "lifestyle coaching",
            "nutrition coaching",
            "diet coaching",
            "patient coaching",
            "remote coaching",
            "peer coaching",
            "peer support",
            "patient navigation",
            "care navigation",
            "community health worker support",
            "dietary counseling",
            "dietary counselling",
            "dietary behavior change",
            "dietary behaviour change",
            "eating behavior change",
            "eating behaviour change",
            "behavioral dietary intervention",
            "behavioural dietary intervention",
            "behavioral nutrition intervention",
            "behavioural nutrition intervention",
            "behavioral weight management",
            "behavioural weight management",
            "behavioral weight loss",
            "behavioural weight loss",
            "personalized nutrition",
            "personalised nutrition",
            "precision nutrition",
            "tailored nutrition",
            "tailored dietary advice",
            "tailored dietary intervention",
            "tailored dietary intervention for obesity",
            "personalized dietary advice",
            "personalised dietary advice",
            "personalized dietary intervention",
            "personalised dietary intervention",
            "individualized diet",
            "individualised diet",
            "individualized dietary intervention",
            "individualized dietary intervention for type 2 diabetes",
            "individualised dietary intervention",
            "diet personalization",
            "diet personalisation",
        ],
        "document_terms": [
            "adherence intervention",
            "dietary adherence intervention",
            "maintenance trial",
            "weight loss maintenance trial",
            "weight regain prevention trial",
            "diabetes remission trial",
            "type 2 diabetes remission trial",
            "diabetes remission maintenance trial",
            "diabetes remission consensus",
            "diabetes remission consensus report",
            "diabetes remission guideline",
            "type 2 diabetes remission guideline",
            "behavior change trial",
            "behaviour change trial",
            "behavioral weight management trial",
            "behavioural weight management trial",
            "behavioral dietary intervention",
            "behavioural dietary intervention",
            "behavioral nutrition intervention",
            "behavioural nutrition intervention",
            "dietary behavior change intervention",
            "dietary behaviour change intervention",
            "self-regulation intervention",
            "relapse prevention intervention",
            "coaching intervention",
            "health coaching intervention",
            "lifestyle coaching intervention",
            "nutrition coaching intervention",
            "motivational interviewing intervention",
            "patient navigation intervention",
            "peer support intervention",
            "longitudinal study",
            "adherence study",
            "tailored dietary intervention",
            "personalized nutrition intervention",
            "personalized nutrition framework",
            "precision nutrition intervention",
            "tailored nutrition framework",
            "personalised nutrition intervention",
            "individualized dietary intervention",
            "individualised dietary intervention",
        ],
    },
    "food_prescription_programs": {
        "terms": [
            "food is medicine",
            "food as medicine",
            "produce prescription",
            "healthy food incentive",
            "produce voucher",
            "produce prescriptions",
            "healthy food incentives",
            "produce vouchers",
            "nutrition incentive",
            "nutrition incentives",
            "food is medicine intervention",
            "food as medicine intervention",
            "produce rx",
            "fruit and vegetable prescription",
            "healthy food prescription",
            "food prescription program",
            "produce prescription program",
            "healthy food incentive program",
            "nutrition incentive program",
            "produce voucher program",
            "fruit and vegetable voucher program",
            "fruit and vegetable voucher",
            "fruit and vegetable vouchers",
            "medically tailored meal",
            "medically tailored meals",
            "medically tailored grocery",
            "medically tailored groceries",
            "medically tailored pantry",
            "medically tailored pantries",
            "medically tailored food package",
            "medically tailored food packages",
            "teaching kitchen",
            "teaching kitchens",
        ],
        "document_terms": [
            "food is medicine intervention",
            "food as medicine intervention",
            "produce prescription program",
            "food prescription program",
            "healthy food incentive program",
            "nutrition incentive program",
            "produce voucher program",
            "fruit and vegetable voucher program",
            "medically tailored pantry",
            "medically tailored pantries",
            "medically tailored food package",
            "medically tailored food packages",
            "implementation study",
            "implementation trial",
            "quality improvement study",
            "technical report",
            "policy brief",
        ],
    },
    "food_literacy_agency": {
        "terms": [
            "food literacy",
            "nutrition literacy",
            "food and nutrition literacy",
            "health literacy",
            "food agency",
            "food skills",
            "food skills intervention",
            "culinary skills",
            "cooking skills",
            "cooking skills intervention",
            "culinary nutrition",
            "culinary nutrition intervention",
            "teaching kitchen",
            "teaching kitchens",
            "teaching kitchen program",
            "teaching kitchen programme",
            "culinary medicine",
            "culinary medicine curriculum",
            "culinary medicine curricula",
            "culinary medicine program",
            "culinary medicine programme",
            "culinary medicine evaluation",
            "cooking class",
            "cooking classes",
            "hands-on cooking",
            "hands on cooking",
            "healthy cooking",
            "cooking confidence",
            "cooking self-efficacy",
            "kitchen confidence",
            "home cooking",
            "meal preparation",
            "food preparation skills",
            "food preparation confidence",
            "meal planning",
            "meal planning skills",
            "shopping skills",
            "grocery shopping skills",
            "healthy grocery shopping",
            "food budgeting",
            "food resource management",
            "experiential nutrition education",
            "food label",
            "nutrition label",
            "label reading",
            "food label literacy",
            "front-of-pack",
            "front-of-pack labeling",
            "front-of-pack labelling",
            "menu labeling",
            "menu labelling",
            "food policy",
            "nutrition policy",
            "food choice",
            "retail food environment",
            "healthy food access",
            "healthy food procurement",
            "self-efficacy",
            "patient activation",
            "empowerment",
            "nutrition education",
        ],
        "document_terms": [
            "questionnaire validation",
            "scale development",
            "psychometric validation",
            "survey instrument",
            "food literacy instrument",
            "culinary skills instrument",
            "cooking skills intervention",
            "cooking confidence scale",
            "cooking self-efficacy scale",
            "meal planning questionnaire",
            "shopping skills scale",
            "food budgeting scale",
            "food resource management questionnaire",
            "food label literacy scale",
            "culinary medicine curriculum",
            "culinary medicine program",
            "culinary medicine programme",
            "culinary medicine evaluation",
            "culinary nutrition intervention",
            "food skills intervention",
            "experiential nutrition education",
            "teaching kitchen curriculum",
            "teaching kitchen program",
            "teaching kitchen programme",
            "policy brief",
            "technical report",
            "policy evaluation",
        ],
    },
    "commensality_context": {
        "terms": [
            "commensality",
            "comensalidade",
            "shared meals",
            "family meals",
            "meal context",
            "eating context",
            "social eating",
            "eat together",
            "meal sharing",
            "communal eating",
            "mealtime routine",
            "food environment",
            "household food practices",
            "cultural food practices",
            "food culture",
            "meal routine",
        ],
        "document_terms": [
            "qualitative study",
            "mixed methods study",
            "ethnographic study",
            "observational study",
        ],
    },
    "equity_access": {
        "terms": [
            "health equity",
            "nutrition security",
            "food insecurity",
            "food insecurity screening",
            "screening for food insecurity",
            "hunger vital sign",
            "nutrition security screening",
            "social needs screening",
            "food desert",
            "food swamp",
            "social determinants of health",
            "socioeconomic status",
            "access to healthy food",
            "healthy food access",
            "affordability",
            "cultural adaptation",
            "underserved populations",
            "low-income",
            "rural health",
            "community health worker",
            "primary care",
            "racial disparities",
            "ethnic disparities",
            "food access intervention",
            "healthy food access intervention",
            "food insecurity intervention",
            "nutrition security intervention",
            "social needs intervention",
            "social needs referral",
            "screening and referral",
            "closed-loop referral",
            "closed loop referral",
            "community referral",
            "community referrals",
            "community resource referral",
            "community resource referrals",
            "social prescribing",
            "social prescribing program",
            "social prescribing programme",
            "social prescribing link worker",
            "link worker",
            "link workers",
            "community connector",
            "community connectors",
            "community food program",
            "community food programme",
            "community-supported food program",
            "community supported food program",
            "food pantry referral",
            "food pantry referral program",
            "food pharmacy",
            "food pharmacy program",
            "food pharmacy programme",
            "food bank partnership",
            "patient navigation",
            "care navigation",
            "community health worker-led nutrition",
            "community health worker led nutrition",
            "food is medicine referral",
            "food as medicine referral",
            "medically tailored food referral",
            "produce prescription referral",
            "nutrition security referral",
        ],
        "document_terms": [
            "equity-focused intervention",
            "community-based intervention",
            "food insecurity screening program",
            "social needs screening program",
            "implementation study",
            "policy evaluation",
            "community trial",
            "food access intervention",
            "food insecurity intervention",
            "nutrition security intervention",
            "social needs intervention",
            "social prescribing program",
            "social prescribing programme",
            "closed-loop referral program",
            "closed loop referral program",
            "community resource referral program",
            "community food program",
            "community food programme",
            "food pharmacy program",
            "food pantry referral program",
            "patient navigation intervention",
            "care navigation intervention",
            "community health worker intervention",
        ],
    },
    "evidence_synthesis": {
        "terms": [
            "systematic review",
            "meta-analysis",
            "meta analysis",
            "network meta-analysis",
            "network meta analysis",
            "umbrella review",
            "overview of reviews",
            "review of reviews",
            "scoping review",
            "integrative review",
            "living systematic review",
            "rapid review",
            "guideline update",
            "clinical practice update",
            "living guideline",
            "standards of care",
            "standards of medical care",
            "standards of medical care in diabetes",
            "consensus report",
            "consensus guidance",
            "consensus update",
            "practice advisory",
            "practice guidance",
            "guidance statement",
            "joint statement",
            "joint guideline",
            "clinical guidance",
            "clinical practice recommendation",
            "clinical practice recommendations",
            "scientific advisory",
            "policy statement",
            "best practice advice",
            "nutrition practice guideline",
            "dietetic practice guideline",
            "clinical decision pathway",
            "decision pathway",
        ],
        "document_terms": [
            "systematic review",
            "meta-analysis",
            "meta analysis",
            "network meta-analysis",
            "network meta analysis",
            "umbrella review",
            "overview of reviews",
            "review of reviews",
            "living systematic review",
            "rapid review",
            "practice guideline",
            "guideline update",
            "clinical practice update",
            "living guideline",
            "standards of care",
            "standards of medical care",
            "standards of medical care in diabetes",
            "consensus report",
            "consensus statement",
            "consensus guidance",
            "consensus update",
            "scientific statement",
            "scientific advisory",
            "position paper",
            "policy statement",
            "practice advisory",
            "practice guidance",
            "guidance statement",
            "joint statement",
            "joint guideline",
            "clinical guidance",
            "clinical practice recommendation",
            "clinical practice recommendations",
            "nutrition practice guideline",
            "dietetic practice guideline",
            "best practice advice",
            "clinical decision pathway",
            "decision pathway",
        ],
    },
    "cardiometabolic_liver": {
        "terms": [
            "masld",
            "mash",
            "mafld",
            "nafld",
            "nash",
            "fatty liver",
            "steatotic liver disease",
            "steatohepatitis",
            "nonalcoholic fatty liver disease",
            "non-alcoholic fatty liver disease",
            "nonalcoholic steatohepatitis",
            "non-alcoholic steatohepatitis",
            "metabolic dysfunction-associated fatty liver disease",
            "metabolic dysfunction associated fatty liver disease",
            "metabolic dysfunction-associated steatotic liver disease",
            "metabolic dysfunction associated steatotic liver disease",
            "metabolic dysfunction-associated steatohepatitis",
            "metabolic dysfunction associated steatohepatitis",
        ],
        "document_terms": [
            "clinical practice guideline",
            "practice guidance",
            "guidance statement",
            "consensus statement",
            "consensus guidance",
            "consensus report",
            "scientific statement",
            "guideline update",
            "clinical practice update",
            "best practice advice",
            "clinical decision pathway",
            "decision pathway",
            "clinical practice recommendation",
            "clinical practice recommendations",
            "systematic review",
            "meta-analysis",
            "umbrella review",
        ],
    },
    "cardiometabolic_precision": {
        "terms": [
            "prediabetes",
            "pre-diabetes",
            "prediabetic state",
            "impaired fasting glucose",
            "impaired glucose tolerance",
            "dysglycemia",
            "dysglycaemia",
            "glucose intolerance",
            "insulin resistance",
            "diabetes remission",
            "type 2 diabetes remission",
            "diabetes reversal",
            "glycemic remission",
            "glycaemic remission",
            "remission of type 2 diabetes",
            "diet-induced diabetes remission",
            "diet induced diabetes remission",
            "lifestyle-induced diabetes remission",
            "lifestyle induced diabetes remission",
            "clinical obesity",
            "adiposity-based chronic disease",
            "adiposity based chronic disease",
            "abdominal obesity",
            "central obesity",
            "visceral obesity",
            "visceral adiposity",
            "visceral fat",
            "ectopic fat",
            "waist circumference",
            "waist-to-height ratio",
            "waist to height ratio",
            "waist-to-hip ratio",
            "waist to hip ratio",
            "dyslipidaemia",
            "hyperlipidemia",
            "hyperlipidaemia",
            "hypercholesterolemia",
            "hypercholesterolaemia",
            "hypertriglyceridemia",
            "hypertriglyceridaemia",
            "atherogenic dyslipidemia",
            "atherogenic dyslipidaemia",
            "remnant cholesterol",
            "triglyceride-rich lipoprotein",
            "triglyceride rich lipoprotein",
            "apolipoprotein b",
            "apo b",
            "cardiometabolic risk",
            "cardiometabolic health",
            "cardiovascular-kidney-metabolic syndrome",
            "cardiovascular kidney metabolic syndrome",
            "cardiovascular-kidney-metabolic health",
            "cardiovascular kidney metabolic health",
            "cardiovascular-kidney-metabolic risk",
            "cardiovascular kidney metabolic risk",
            "ckm syndrome",
            "ckm health",
            "ckm risk",
            "cardiorenal metabolic syndrome",
            "cardio-renal-metabolic syndrome",
            "personalized nutrition for cardiometabolic risk",
            "precision nutrition for type 2 diabetes",
        ],
        "document_terms": [
            "clinical practice guideline",
            "practice guidance",
            "guidance statement",
            "consensus statement",
            "consensus report",
            "scientific statement",
            "clinical decision pathway",
            "cardiovascular-kidney-metabolic syndrome guideline",
            "cardiovascular kidney metabolic syndrome guideline",
            "cardiovascular-kidney-metabolic syndrome statement",
            "cardiovascular kidney metabolic syndrome statement",
            "ckm syndrome guideline",
            "ckm syndrome statement",
            "diabetes remission guideline",
            "diabetes remission consensus",
            "diabetes remission consensus report",
            "type 2 diabetes remission guideline",
            "systematic review",
            "meta-analysis",
            "network meta-analysis",
            "umbrella review",
        ],
    },
    "lifestyle_nutrition_patterns": {
        "terms": [
            "lifestyle medicine",
            "lifestyle intervention",
            "lifestyle modification",
            "therapeutic lifestyle changes",
            "medical nutrition therapy",
            "nutrition therapy",
            "diet therapy",
            "dietetic treatment",
            "dietary treatment",
            "medical nutrition therapy intervention",
            "nutrition therapy intervention",
            "diet therapy intervention",
            "nutrition care",
            "nutrition care process",
            "nutrition care process model",
            "nutrition care pathway",
            "nutrition care pathways",
            "nutrition care protocol",
            "healthy eating pattern",
            "healthy eating patterns",
            "healthy dietary pattern",
            "healthy dietary patterns",
            "diet quality",
            "dietary pattern",
            "mediterranean diet",
            "mediterranean dietary pattern",
            "dash diet",
            "dietary approaches to stop hypertension",
            "mind diet",
            "plant-based diet",
            "plant based diet",
            "vegetarian diet",
            "vegetarian dietary pattern",
            "vegan diet",
            "vegan dietary pattern",
            "healthy plant-based diet",
            "healthy plant based diet",
            "pro-vegetarian dietary pattern",
            "provegetarian dietary pattern",
            "whole-food plant-based",
            "whole food plant based",
            "meal replacement",
            "meal replacements",
            "partial meal replacement",
            "partial meal replacements",
            "total diet replacement",
            "total diet replacements",
            "formula diet",
            "formula diets",
            "very low energy diet",
            "very-low-energy diet",
            "low energy diet",
            "low-energy diet",
            "very low calorie diet",
            "very-low-calorie diet",
            "low-carbohydrate diet",
            "low carbohydrate diet",
            "carbohydrate-restricted diet",
            "carbohydrate restricted diet",
            "very low carbohydrate diet",
            "very-low-carbohydrate diet",
            "ketogenic diet",
            "time-restricted eating",
            "time restricted eating",
            "early time-restricted feeding",
            "early time restricted feeding",
            "intermittent fasting",
            "diabetes remission",
            "type 2 diabetes remission",
            "diabetes reversal",
            "glycemic remission",
            "glycaemic remission",
            "remission of type 2 diabetes",
            "weight loss maintenance",
            "long-term weight loss maintenance",
            "long term weight loss maintenance",
            "weight regain prevention",
            "portfolio diet",
            "nordic diet",
            "new nordic diet",
            "eat-lancet",
            "planetary health diet",
            "food is medicine",
            "food as medicine",
            "produce prescription",
            "produce prescriptions",
            "medically tailored meals",
            "medically tailored groceries",
        ],
        "document_terms": [
            "dietary guideline",
            "food-based dietary guideline",
            "clinical practice guideline",
            "practice guideline",
            "scientific statement",
            "systematic review",
            "umbrella review",
            "diabetes remission guideline",
            "diabetes remission consensus",
            "diabetes remission consensus report",
            "type 2 diabetes remission guideline",
            "weight loss maintenance trial",
            "weight loss maintenance systematic review",
            "medical nutrition therapy guideline",
            "medical nutrition therapy consensus",
            "medical nutrition therapy intervention",
            "nutrition therapy guideline",
            "nutrition therapy intervention",
            "diet therapy guideline",
            "diet therapy intervention",
            "nutrition care process model",
            "nutrition care pathway",
        ],
    },
}

WORKSTREAM_SEMANTIC_PRIORITIES: dict[str, list[tuple[str, int]]] = {
    "busca1": [
        ("food_prescription_programs", 5),
        ("food_literacy_agency", 5),
        ("commensality_context", 5),
        ("lifestyle_nutrition_patterns", 5),
        ("implementation_science", 4),
        ("evidence_synthesis", 4),
        ("equity_access", 4),
        ("adherence_persistence", 3),
    ],
    "busca2a": [
        ("cardiometabolic_liver", 5),
        ("cardiometabolic_precision", 5),
        ("nutrition_care_delivery", 5),
        ("implementation_science", 5),
        ("evidence_synthesis", 5),
        ("adherence_persistence", 4),
        ("equity_access", 4),
        ("lifestyle_nutrition_patterns", 4),
        ("food_literacy_agency", 2),
        ("commensality_context", 1),
    ],
    "busca2b": [
        ("cardiometabolic_liver", 5),
        ("cardiometabolic_precision", 5),
        ("food_prescription_programs", 5),
        ("nutrition_care_delivery", 5),
        ("implementation_science", 5),
        ("adherence_persistence", 5),
        ("evidence_synthesis", 5),
        ("lifestyle_nutrition_patterns", 5),
        ("food_literacy_agency", 4),
        ("equity_access", 4),
        ("commensality_context", 2),
    ],
    "artigo3_framework": [
        ("food_literacy_agency", 5),
        ("nutrition_care_delivery", 5),
        ("commensality_context", 5),
        ("implementation_science", 4),
        ("adherence_persistence", 4),
        ("evidence_synthesis", 3),
        ("lifestyle_nutrition_patterns", 3),
        ("equity_access", 3),
    ],
}


def _canonical_workstream(workstream: str) -> str:
    return WORKSTREAM_ALIASES.get(workstream, workstream)


def _uniq(items: list[str]) -> list[str]:
    seen = set()
    out = []
    for item in items:
        value = str(item).strip()
        if not value:
            continue
        low = value.lower()
        if low in seen:
            continue
        seen.add(low)
        out.append(value)
    return out


def semantic_block_names(workstream: str) -> list[str]:
    ws_key = _canonical_workstream(workstream)
    return [name for name, _ in WORKSTREAM_SEMANTIC_PRIORITIES.get(ws_key, [])]


def prioritized_semantic_blocks(workstream: str) -> list[dict[str, int | str]]:
    ws_key = _canonical_workstream(workstream)
    return [
        {"name": name, "priority": priority}
        for name, priority in WORKSTREAM_SEMANTIC_PRIORITIES.get(ws_key, [])
    ]


def semantic_terms(
    workstream: str,
    *,
    field: str = "terms",
    min_priority: int = 1,
) -> list[str]:
    ws_key = _canonical_workstream(workstream)
    terms: list[str] = []
    for block_name, priority in WORKSTREAM_SEMANTIC_PRIORITIES.get(ws_key, []):
        if priority < min_priority:
            continue
        block = SEMANTIC_RESEARCH_BLOCKS.get(block_name, {})
        terms.extend(block.get(field, []))
    return _uniq(terms)
